<a href="https://colab.research.google.com/github/Saputoa21/Introduction_Machine_Learning-Information_Retrieval/blob/main/Retrieval_System_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Retrieval System Project**: Agatha Christie's Books

## 1. Downloading Texts

In [33]:
!git clone https://github.com/Saputoa21/Machine-Learning.git
!ls Machine-Learning

fatal: destination path 'Machine-Learning' already exists and is not an empty directory.
 01_LM_NLP_python_basics_Anastasiya_SAPUTO.ipynb
 02_Gender_Identification_with_Decision_Tree_Anastasiya_SAPUTO.ipynb
 03_Probabelistic_Modeling_Naive_Bayes_Anastasiya_SAPUTO.ipynb
 Agatha_Christie_Corpus.zip
 extracted_files
 Inverted_index_exercise.ipynb
'O4_LM_LDA_Topic_modelling_SAPUTO_2024 (1).ipynb'
 Retrieval_System_Project.ipynb

In [34]:
import zipfile
import os

zip_path = "Machine-Learning/Agatha_Christie_Corpus.zip"
extract_path = "Machine-Learning/extracted_files"

# Create a directory to extract if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

# Extract the ZIP file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# List extracted files
!ls Machine-Learning/extracted_files

'Poirot Investigates_pg61262.txt'
'The Big Four_pg70114.txt'
"The Hunter's Lodge Case_pg67160.txt"
'The man in the Brown Suit_pg61168.txt'
'The Missing Will_pg67173.txt'
'The Murder of Roger Ackroyd_pg69087.txt'
'The Murder on the Links_pg58866.txt'
'The Mysterious Affair at Styles_pg863.txt'
'The Mystery of the Blue Train_pg72824.txt'
'The Plymouth Express Affair_pg66446.txt'
'The Secret Adversary_pg1155.txt'
'The Secret of Chimneys_pg65238.txt'
'The Seven Dials Mystery_pg75288.txt'

In [35]:
file_path = "Machine-Learning/extracted_files/Poirot Investigates_pg61262.txt"

with open(file_path, "r", encoding="utf-8") as file:
    content = file.read()
    print(content[:1000])

﻿The Project Gutenberg eBook of Poirot Investigates

This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.

Title: Poirot Investigates

Author: Agatha Christie

Release date: January 28, 2020 [eBook #61262]
                Most recently updated: October 17, 2024

Language: English

Credits: Produced by an anonymous Project Gutenberg volunteer.


*** START OF THE PROJECT GUTENBERG EBOOK POIROT INVESTIGATES ***

  POIROT INVESTIGATES




  BY THE SAME AUTHOR

  THE MYSTERIOUS AFFAIR AT STYLES

  THE SECRET ADVERSARY

  THE MURDER ON THE LINKS

  THE BODLEY HEAD




  POIROT INVESTIGATES

  BY AGATHA CH

## 2. Creating the Dataframe from Texts

In [37]:
import pandas as pd

# Lists to store filenames and text contents
filenames = []
texts = []

# Loop through all .txt files in the directory
for filename in os.listdir(extract_path):
  if filename.endswith(".txt"):
    division = filename.find("_")
    file_path = os.path.join(extract_path, filename[:])
    with open(file_path, "r", encoding="utf-8", errors="ignore") as file:
            filenames.append(filename)
            texts.append(file.read())

# Create a DataFrame
df = pd.DataFrame({"book_title": filenames, "content": texts})

df.insert(0, 'book_id', range(0, len(df)))

In [38]:
print(df) #print the dataframe

    book_id                                 book_title  \
0         0               The Missing Will_pg67173.txt
1         1        The Murder on the Links_pg58866.txt
2         2        The Seven Dials Mystery_pg75288.txt
3         3            Poirot Investigates_pg61262.txt
4         4      The man in the Brown Suit_pg61168.txt
5         5  The Mysterious Affair at Styles_pg863.txt
6         6            The Secret Adversary_pg1155.txt
7         7                   The Big Four_pg70114.txt
8         8    The Murder of Roger Ackroyd_pg69087.txt
9         9         The Secret of Chimneys_pg65238.txt
10       10  The Mystery of the Blue Train_pg72824.txt
11       11        The Hunter's Lodge Case_pg67160.txt
12       12    The Plymouth Express Affair_pg66446.txt

                                              content
0   ﻿The Project Gutenberg eBook of The Missing Wi...
1   ﻿The Project Gutenberg eBook of The Murder on ...
2   ﻿The Project Gutenberg eBook of The Seven Dial...
3   ﻿The Project Gutenberg eBook of Poirot Investi...
4   ﻿The Project Gutenberg eBook of The Man in the...
5   ﻿The Project Gutenberg eBook of The Mysterious...
6   ﻿The Project Gutenberg eBook of The Secret Adv...
7   ﻿The Project Gutenberg eBook of The Big Four\n...
8   ﻿The Project Gutenberg eBook of The murder of ...
9   ﻿The Project Gutenberg eBook of The Secret of ...
10  ﻿The Project Gutenberg eBook of The mystery of...
11  ﻿The Project Gutenberg eBook of The Hunter's L...
12  ﻿The Project Gutenberg eBook of The Plymouth E...

In [39]:
# Clean book title by removing the "_pgXXXXX.txt" part
df["book_title"] = df["book_title"].str.replace(r"_pg\d+\.txt$", "", regex=True)

In [40]:
print(df)

    book_id                       book_title  \
0         0                 The Missing Will
1         1          The Murder on the Links
2         2          The Seven Dials Mystery
3         3              Poirot Investigates
4         4        The man in the Brown Suit
5         5  The Mysterious Affair at Styles
6         6             The Secret Adversary
7         7                     The Big Four
8         8      The Murder of Roger Ackroyd
9         9           The Secret of Chimneys
10       10    The Mystery of the Blue Train
11       11          The Hunter's Lodge Case
12       12      The Plymouth Express Affair

                                              content
0   ﻿The Project Gutenberg eBook of The Missing Wi...
1   ﻿The Project Gutenberg eBook of The Murder on ...
2   ﻿The Project Gutenberg eBook of The Seven Dial...
3   ﻿The Project Gutenberg eBook of Poirot Investi...
4   ﻿The Project Gutenberg eBook of The Man in the...
5   ﻿The Project Gutenberg eBook of The Mysterious...
6   ﻿The Project Gutenberg eBook of The Secret Adv...
7   ﻿The Project Gutenberg eBook of The Big Four\n...
8   ﻿The Project Gutenberg eBook of The murder of ...
9   ﻿The Project Gutenberg eBook of The Secret of ...
10  ﻿The Project Gutenberg eBook of The mystery of...
11  ﻿The Project Gutenberg eBook of The Hunter's L...
12  ﻿The Project Gutenberg eBook of The Plymouth E...

In [43]:
print(df['content'][0][:3000]) #printing the first book content

﻿The Project Gutenberg eBook of The Missing Will

This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.

Title: The Missing Will

Author: Agatha Christie

Release date: January 15, 2022 [eBook #67173]
                Most recently updated: October 18, 2024

Language: English

Original publication: United States: The Consolidated Magazines Corporation (The Blue Book Magazine), 1925

Credits: Roger Frank and Sue Clark


*** START OF THE PROJECT GUTENBERG EBOOK THE MISSING WILL ***
                           The Missing Will

             Hercule Poirot Solves an Extraordinary Case
                          by Agatha Christie

[Illustration]

The problem presented to us by Miss Violet Marsh made a rather
pleasant change from our usual routine work. Poirot had received a
brisk and businesslike note from the lady asking for an appointment,
and he had replied, asking her to call upon him at eleven o’clock the
following day.

She arrived punctually—a tall, handsome young woman, plainly but
neatly dressed, with an assured and businesslike manner—clearly, a
young woman who meant to get on in the world. I am not a great admirer
of the so-called New Woman myself, and in spite of her good looks, I
was not particularly prepossessed in her favor.

“My business is of a somewhat unusual nature, M. Poirot,” she began,
after she had accepted a chair. “I had better begin at the beginning
and tell you the whole story.”

“If you please, mademoiselle.”

“I am an orphan. My father was one of two brothers, sons of a small
yeoman farmer in Devonshire. The farm was a poor one, and the eldest
brother, Andrew, emigrated to Australia, where he did very well
indeed, and by means of successful speculation in land became a very
rich man. The younger brother, Roger, my father, had no leanings
toward the agricultural life. He managed to educate himself a little,
and obtained a post as a clerk in a small firm. He married slightly
above him; my mother was the daughter of a poor artist. My father died
when I was six years old. When I was fourteen, my mother followed him
to the grave. My only living relation then was my Uncle Andrew, who
had recently returned from Australia and bought a small place in his
native county, Crabtree Manor. He was exceedingly kind to his
brother’s orphan child, took me to live with him, and treated me in
every way as though I were his own daughter.

“Crabtree Manor,” she pursued, “in spite of its name, is really only
an old farmhouse. Farming was in my uncle’s blood, and he was
intensely interested in various modern farming experiments. Although
kindness itself to me, h

Problem with paragraphing - possible if not removing empty lines first

In [48]:
book_1 = df['content'][1]

In [49]:
paragraphs = [p.strip() for p in book_1.split('\n\n') if p.strip()]

# Create DataFrame
df_par = pd.DataFrame(paragraphs, columns=["Paragraph"])

df_par.tail()

                                              Paragraph
2708  Section 5. General Information About Project G...
2709  Professor Michael S. Hart was the originator o...
2710  Project Gutenberg™ eBooks are often created fr...
2711  Most people start at our website which has the...
2712  This website includes information about Projec...

## 3. Testing Cleaning and Splitting on One Book

In [124]:
# Remove empty lines and join all lines into one
cleaned_book_1 = "\n".join([line.strip() for line in book_1.split("\n") if line.strip()])

print(cleaned_book_1[:2000])

﻿The Project Gutenberg eBook of The Murder on the Links
This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.
Title: The Murder on the Links
Author: Agatha Christie
Release date: February 11, 2019 [eBook #58866]
Most recently updated: November 30, 2022
Language: English
Credits: Alex Cabal
*** START OF THE PROJECT GUTENBERG EBOOK THE MURDER ON THE LINKS ***
cover
The Murder on the Links
by Agatha Christie
TO MY HUSBAND
A fellow enthusiast for detective stories, and to whom I am indebted for much
helpful advice and criticism.
Contents
1 A Fellow Traveller
2 An Appeal for Help
3 At the Villa Geneviève
4 The Letter Signed “Bella”
5 Mrs. Renauld’s Story
6 The Scene of the Crime
7 The Mysterious Madame Daubreuil
8 An Unexpected Meeting
9 M. Giraud Finds Some Clues
10 Gabriel Stonor
11 Jack Renauld
12 Poirot Elucidates Certain Points
13 The Girl with the Anxious Eyes
14 The Second Body
15 A Photograph
16 The Beroldy Case
17 We Make Further Investigations
18 Giraud Acts
19 I Use My Grey Cells
20 An Amazing Statement
21 Hercule Poirot on the Case!
22 I Find Love
23 Difficulties Ahead
24 “Save Him!”
25 An Unexpected Dénouement
26 I Receive a Letter
27 Jack Renauld’s Story
28 Journey’s End
1 A Fellow Traveller
I believe that a well-known anecdote exists to the effect that a young
writer, determined to make the commencement of his story forcible and
original enough to catch and rivet the attention of the most blasé of
editors, penned the following sentence:
“‘Hell!’ said the Duchess.”
Strangely enough, this tale of mine opens in much the same fashion.
Only the lady who gave utterance to the excl

In [125]:
paragraphs = [p.strip() for p in cleaned_book_1.split('\n\n') if p.strip()]

# Create DataFrame
df_par = pd.DataFrame(paragraphs, columns=["Paragraph"])

df_par.tail()

                                           Paragraph
0  ﻿The Project Gutenberg eBook of The Murder on ...

### Deleting Irrelevant Book Parts

In [126]:
import re

# Splitting lines and deleting metadata of the Guteberg's project
lines = cleaned_book_1.split("\n")
start_idx = 0
end_idx = 0

for i, line in enumerate(lines):
  if "*** START OF THE PROJECT GUTENBERG EBOOK" in line:
    start_idx = i + 1
  if "*** END OF THE PROJECT GUTENBERG EBOOK" in line:
    end_idx = i
    break

In [127]:
book_1_wo_metadata = "\n".join(lines[start_idx:end_idx])

print(book_1_wo_metadata[:1500])

lines = book_1_wo_metadata.split("\n")

cover
The Murder on the Links
by Agatha Christie
TO MY HUSBAND
A fellow enthusiast for detective stories, and to whom I am indebted for much
helpful advice and criticism.
Contents
1 A Fellow Traveller
2 An Appeal for Help
3 At the Villa Geneviève
4 The Letter Signed “Bella”
5 Mrs. Renauld’s Story
6 The Scene of the Crime
7 The Mysterious Madame Daubreuil
8 An Unexpected Meeting
9 M. Giraud Finds Some Clues
10 Gabriel Stonor
11 Jack Renauld
12 Poirot Elucidates Certain Points
13 The Girl with the Anxious Eyes
14 The Second Body
15 A Photograph
16 The Beroldy Case
17 We Make Further Investigations
18 Giraud Acts
19 I Use My Grey Cells
20 An Amazing Statement
21 Hercule Poirot on the Case!
22 I Find Love
23 Difficulties Ahead
24 “Save Him!”
25 An Unexpected Dénouement
26 I Receive a Letter
27 Jack Renauld’s Story
28 Journey’s End
1 A Fellow Traveller
I believe that a well-known anecdote exists to the effect that a young
writer, determined to make the commencement of his story forcible and
original enough to catch and rivet the attention of the most blasé of
editors, penned the following sentence:
“‘Hell!’ said the Duchess.”
Strangely enough, this tale of mine opens in much the same fashion.
Only the lady who gave utterance to the exclamation was not a Duchess!
It was a day in early June. I had been transacting some business in
Paris and was returning by the morning service to London where I was
still sharing rooms with my old friend, the Belgian ex-detective,
Hercule Poirot.
The

In [143]:
lines[:10]

['cover',
 'The Murder on the Links',
 'by Agatha Christie',
 'TO MY HUSBAND',
 'A fellow enthusiast for detective stories, and to whom I am indebted for much',
 'helpful advice and criticism.',
 'Contents',
 '1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève']

In [142]:
print(len(lines))

6506

Problem with paragraphing texts - no more possible due to removing /n fisrt

In [129]:
paragraphs = [p.strip() for p in book_1_wo_metadata.split('\n\n') if p.strip()]

# Create DataFrame
df_par = pd.DataFrame(paragraphs, columns=["Paragraph"])

In [130]:
df_par.tail()

                                           Paragraph
0  cover\nThe Murder on the Links\nby Agatha Chri...

### Finding chapters

In [131]:
import re

# Extracting chapters

"""
# As some books are formatted differently, I need to have several options for identification the chapters, e.g:
PROLOGUE
CHAPTER I. I GO TO STYLES
I  DR. SHEPPARD AT THE BREAKFAST TABLE
I The Adventure of “The Western Star”
CHAPTER I.   THE YOUNG ADVENTURERS, LTD.
1 A Fellow Traveller
XVIII JIMMY'S ADVENTURES
1. The Man with the White Hair
CHAPTER I
11. A CHESS PROBLEM
1 ANTHONY CADE SIGNS ON
*       *       *       *       *

"""

chapter_regex = re.compile(
    r"^("
    r"PROLOGUE$|"
    r"CHAPTER\s+[IVXLCDM]+\.\s+[^\n]+|"    # CHAPTER I. Title
    r"CHAPTER\s+[IVXLCDM]+$|"              # CHAPTER I
    r"[IVXLCDM]{1,4}\s{1,}[A-Z][^\n]+|"    # I Title
    r"\d+\.\s+[A-Z][^\n]+|"                # 1. Title
    r"\d+\s+[A-Z][^\n]+|"                  # 1 Title
    r"\*+(\s+\*+)+$"                       # * * * * *
    r")$",
    re.MULTILINE
)

In [132]:
#finding chapters with the regex object
matches = re.findall(chapter_regex, book_1_wo_metadata)

print(matches)

[('1 A Fellow Traveller', ''), ('2 An Appeal for Help', ''), ('3 At the Villa Geneviève', ''), ('4 The Letter Signed “Bella”', ''), ('5 Mrs. Renauld’s Story', ''), ('6 The Scene of the Crime', ''), ('7 The Mysterious Madame Daubreuil', ''), ('8 An Unexpected Meeting', ''), ('9 M. Giraud Finds Some Clues', ''), ('10 Gabriel Stonor', ''), ('11 Jack Renauld', ''), ('12 Poirot Elucidates Certain Points', ''), ('13 The Girl with the Anxious Eyes', ''), ('14 The Second Body', ''), ('15 A Photograph', ''), ('16 The Beroldy Case', ''), ('17 We Make Further Investigations', ''), ('18 Giraud Acts', ''), ('19 I Use My Grey Cells', ''), ('20 An Amazing Statement', ''), ('21 Hercule Poirot on the Case!', ''), ('22 I Find Love', ''), ('23 Difficulties Ahead', ''), ('25 An Unexpected Dénouement', ''), ('26 I Receive a Letter', ''), ('27 Jack Renauld’s Story', ''), ('28 Journey’s End', ''), ('1 A Fellow Traveller', ''), ('2 An Appeal for Help', ''), ('3 At the Villa Geneviève', ''), ('4 The Letter Signed “Bella”', ''), ('5 Mrs. Renauld’s Story', ''), ('6 The Scene of the Crime', ''), ('7 The Mysterious Madame Daubreuil', ''), ('8 An Unexpected Meeting', ''), ('9 M. Giraud Finds Some Clues', ''), ('10 Gabriel Stonor', ''), ('11 Jack Renauld', ''), ('12 Poirot Elucidates Certain Points', ''), ('13 The Girl with the Anxious Eyes', ''), ('14 The Second Body', ''), ('15 A Photograph', ''), ('16 The Beroldy Case', ''), ('17 We Make Further Investigations', ''), ('18 Giraud Acts', ''), ('19 I Use My Grey Cells', ''), ('20 An Amazing Statement', ''), ('21 Hercule Poirot on the Case!', ''), ('22 I Find Love', ''), ('23 Difficulties Ahead', ''), ('25 An Unexpected Dénouement', ''), ('26 I Receive a Letter', ''), ('27 Jack Renauld’s Story', ''), ('28 Journey’s End', '')]

In [134]:
#there are sometimes lines breaks or white spaces which should be avoided (in some books)
def contains_newline(text):
    return '\n' in text

chapters = [m[0] for m in matches if not contains_newline(m[0])] # The outputs are tuples so we need the 1 part from them

In [136]:
#removing duplicates as usually chapter names come twice (in the table of contens and in the beginning of each chpater)
seen = []
chapter_list = []
for chapter in chapters:
    if chapter not in seen:
        seen.append(chapter)
        chapter_list.append(chapter)

# I did not used the option with a set as the order of chapters gets lost, while the reordering it back with transforming into a list and applying sort method does work right.

In [137]:
print(chapter_list)
print(type(chapter_list))
print(len(chapter_list))

['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
<class 'list'>
27

In [138]:
#printing out chapters
for m in chapter_list:
    print(m)

1 A Fellow Traveller
2 An Appeal for Help
3 At the Villa Geneviève
4 The Letter Signed “Bella”
5 Mrs. Renauld’s Story
6 The Scene of the Crime
7 The Mysterious Madame Daubreuil
8 An Unexpected Meeting
9 M. Giraud Finds Some Clues
10 Gabriel Stonor
11 Jack Renauld
12 Poirot Elucidates Certain Points
13 The Girl with the Anxious Eyes
14 The Second Body
15 A Photograph
16 The Beroldy Case
17 We Make Further Investigations
18 Giraud Acts
19 I Use My Grey Cells
20 An Amazing Statement
21 Hercule Poirot on the Case!
22 I Find Love
23 Difficulties Ahead
25 An Unexpected Dénouement
26 I Receive a Letter
27 Jack Renauld’s Story
28 Journey’s End

### Finding the main content of the book

In [145]:
lines[:10]

['cover',
 'The Murder on the Links',
 'by Agatha Christie',
 'TO MY HUSBAND',
 'A fellow enthusiast for detective stories, and to whom I am indebted for much',
 'helpful advice and criticism.',
 'Contents',
 '1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève']

In [165]:
#finding the Contents section
def find_main_book_content(lines, chapter_list):
    found_contents = False
    contents_start_idx = 0
    contents_end_idx = 0
    book_end = len(lines)
    for i, line in enumerate(lines):
        if "Contents" in line or "CONTENTS" in line:
            contents_start_idx = i + 1
            found_contents = True
        if line.strip() == chapter_list[-1]:  #last chapter in the list and conen table
            contents_end_idx = i
            book_start = contents_end_idx + 1
            break

    if not found_contents:  #if no "Contents" section found (true for some books)
        for i, line in enumerate(lines):
            if line.strip() in chapter_list:
                contents_start_idx = i
                book_start = contents_start_idx +1
                break
    return slice(book_start, book_end) #creating out of a tuple with indeces a slice for a list

In [166]:
#extracting and joining the main book content
book_1_main_lines = lines[find_main_book_content(lines, chapter_list)]
book_1_main_content = "\n".join(book_1_main_lines)

In [167]:
print(book_1_main_content[:1000])

1 A Fellow Traveller
I believe that a well-known anecdote exists to the effect that a young
writer, determined to make the commencement of his story forcible and
original enough to catch and rivet the attention of the most blasé of
editors, penned the following sentence:
“‘Hell!’ said the Duchess.”
Strangely enough, this tale of mine opens in much the same fashion.
Only the lady who gave utterance to the exclamation was not a Duchess!
It was a day in early June. I had been transacting some business in
Paris and was returning by the morning service to London where I was
still sharing rooms with my old friend, the Belgian ex-detective,
Hercule Poirot.
The Calais express was singularly empty—in fact, my own compartment
held only one other traveller. I had made a somewhat hurried departure
from the hotel and was busy assuring myself that I had duly collected
all my traps when the train started. Up till then I had hardly noticed
my companion, but I was now violently recalled to the fact of

### Splitting the book into chapters and paragraphs

In [169]:
chapter_list

['1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève',
 '4 The Letter Signed “Bella”',
 '5 Mrs. Renauld’s Story',
 '6 The Scene of the Crime',
 '7 The Mysterious Madame Daubreuil',
 '8 An Unexpected Meeting',
 '9 M. Giraud Finds Some Clues',
 '10 Gabriel Stonor',
 '11 Jack Renauld',
 '12 Poirot Elucidates Certain Points',
 '13 The Girl with the Anxious Eyes',
 '14 The Second Body',
 '15 A Photograph',
 '16 The Beroldy Case',
 '17 We Make Further Investigations',
 '18 Giraud Acts',
 '19 I Use My Grey Cells',
 '20 An Amazing Statement',
 '21 Hercule Poirot on the Case!',
 '22 I Find Love',
 '23 Difficulties Ahead',
 '25 An Unexpected Dénouement',
 '26 I Receive a Letter',
 '27 Jack Renauld’s Story',
 '28 Journey’s End']

In [212]:
import pandas as pd

def extract_chapters_and_paragraphs(text, chapters_list, book_id=1, book_title="Unknown Title", paragraph_num = 5):
    lines = text.split("\n")

    # Step 1: Find indexes of each chapter title in the lines
    chapter_indices = []
    for i, line in enumerate(lines):
        if line in chapters_list:
            chapter_indices.append((line, i))

    # Step 2: Build chapter blocks
    chapters = []
    for idx, (chapter_title, start_idx) in enumerate(chapter_indices):
        end_idx = chapter_indices[idx + 1][1] if idx + 1 < len(chapter_indices) else len(lines)
        chapter_lines = lines[start_idx + 1:end_idx]
        chapter_text = "\n".join(chapter_lines).strip()

        chapters.append({
            "chapter_title": chapter_title,
            "chapter_text": chapter_text
        })

    final_rows = []

    for chap_id, chap in enumerate(chapters, 1):
      # Remove newlines and split text into words
      words = chap["chapter_text"].replace('\n', ' ').split()
      total_words = len(words)

      # Compute base chunk size
      chunk_size = total_words // paragraph_num
      remainder = total_words % paragraph_num

      start = 0
      for para_id in range(1, paragraph_num + 1):
        # Distribute the remainder across first few paragraphs
        end = start + chunk_size + (1 if para_id <= remainder else 0)
        para_words = words[start:end]
        paragraph_text = " ".join(para_words)

        final_rows.append({
            "book_id": book_id,
            "book_title": book_title,
            "chapter_id": chap_id,
            "chapter_title": chap["chapter_title"],
            "paragraph_id": para_id,
            "paragraph_text": paragraph_text
        })

        start = end

    return pd.DataFrame(final_rows)

In [213]:
book_text = book_1_main_content
book_title = df.loc[0,"book_title"]
book_id = df.loc[0,"book_id"]
chapter_list = chapters
paragraph_num = 5

book_1_splitted_df = extract_chapters_and_paragraphs(book_text, chapter_list, book_id, book_title, paragraph_num)

In [214]:
book_1_splitted_df

,book_id,book_title,chapter_id,chapter_title,paragraph_id,paragraph_text
0,0,The Missing Will,1,1 A Fellow Traveller,1,I believe that a well-known anecdote exists to...
1,0,The Missing Will,1,1 A Fellow Traveller,2,I’ve lost my only sister?” “Really?” I said po...
2,0,The Missing Will,1,1 A Fellow Traveller,3,mad?” I inquired with a smile. “A regular litt...
3,0,The Missing Will,1,1 A Fellow Traveller,4,"nodded. “You were through it, I suppose?” “Pre..."
4,0,The Missing Will,1,1 A Fellow Traveller,5,"operations, and stared at me with undisguised ..."
...,...,...,...,...,...,...
130,0,The Missing Will,27,28 Journey’s End,1,I have confused memories of the further events...
131,0,The Missing Will,27,28 Journey’s End,2,facts fail to support any theory of her guilt....
132,0,The Missing Will,27,28 Journey’s End,3,be wandering about carrying a souvenir paper-k...
133,0,The Missing Will,27,28 Journey’s End,4,"did I tell you? The shock of joy, it was too m..."
134,0,The Missing Will,27,28 Journey’s End,5,had been in actual fact a fugitive from justic...

## Cleaning and Splitting All Books to Create a Common Dataframe

In [215]:
#modified functions that I have created based on 1 book testing

def delete_metadata(book):
  cleaned_book = "\n".join([line.strip() for line in book.split("\n") if line.strip()])
  lines = cleaned_book_1.split("\n")
  start_idx = 0
  end_idx = 0
  for i, line in enumerate(lines):
    if "*** START OF THE PROJECT GUTENBERG EBOOK" in line:
      start_idx = i + 1
    if "*** END OF THE PROJECT GUTENBERG EBOOK" in line:
      end_idx = i
      break
  book_wo_metadata = "\n".join(lines[start_idx:end_idx])
  return book_wo_metadata

def contains_newline(text):
    return '\n' in text

def find_chapters(book_wo_metadata, chapter_regex):
  seen = []
  chapter_list = []
  matches = re.findall(chapter_regex, book_wo_metadata)
  matches = [m[0] for m in matches if not contains_newline(m[0])]
  for chapter in matches:
    if chapter not in seen:
        seen.append(chapter)
        chapter_list.append(chapter)
  return chapter_list

def find_main_book_content(book_wo_metadata, chapter_list):
    lines = book_wo_metadata.split("\n")
    found_contents = False
    contents_start_idx = 0
    contents_end_idx = 0
    book_end = len(lines)
    for i, line in enumerate(lines):
        if "Contents" in line or "CONTENTS" in line:
            contents_start_idx = i + 1
            found_contents = True
        if line.strip() == chapter_list[-1]:  #last chapter in the list and conen table
            contents_end_idx = i
            book_start = contents_end_idx + 1
            break
    if not found_contents:  #if no "Contents" section found (true for some books)
        for i, line in enumerate(lines):
            if line.strip() in chapter_list:
                contents_start_idx = i
                book_start = contents_start_idx +1
                break
    main_content_slice = slice(book_start, book_end) #creating out of a tuple with indeces a slice for a list
    book_main_lines = lines[main_content_slice]
    book_main_content = "\n".join(book_1_main_lines)
    return book_main_content

In [228]:
book_text = df.iloc[4]["content"]
book_text

'\ufeffThe Project Gutenberg eBook of The Man in the Brown Suit\n    \nThis ebook is for the use of anyone anywhere in the United States and\nmost other parts of the world at no cost and with almost no restrictions\nwhatsoever. You may copy it, give it away or re-use it under the terms\nof the Project Gutenberg License included with this ebook or online\nat www.gutenberg.org. If you are not located in the United States,\nyou will have to check the laws of the country where you are located\nbefore using this eBook.\n\nTitle: The Man in the Brown Suit\n\nAuthor: Agatha Christie\n\nRelease date: January 14, 2020 [eBook #61168]\n                Most recently updated: October 17, 2024\n\nLanguage: English\n\nCredits: an anonymous Project Gutenberg volunteer\n\n\n*** START OF THE PROJECT GUTENBERG EBOOK THE MAN IN THE BROWN SUIT ***\n\n  THE MAN IN THE BROWN SUIT\n\n\n\n\n  BY THE SAME AUTHOR\n\n  THE MYSTERIOUS AFFAIR AT STYLES\n\n  THE SECRET ADVERSARY\n\n  THE MURDER ON THE LINKS\n\n\n\n\n  THE MAN IN THE BROWN SUIT\n  by\n  AGATHA CHRISTIE\n\n  NEW YORK\n\n  DODD, MEAD AND COMPANY\n\n  1924\n\n\n\n\n\n  Copyright, 1924,\n  By DODD, MEAD AND COMPANY, Inc.\n\n  PRINTED IN THE U. S. A. BY\n  The Quinn & Boden Company\n  BOOK MANUFACTURERS\n  RAHWAY   NEW JERSEY\n\n\n\n\n  To E. A. B.\n\n  IN MEMORY OF A JOURNEY, SOME\n  LION STORIES AND A REQUEST THAT\n  I SHOULD SOME DAY WRITE THE\n  “MYSTERY OF THE MILL HOUSE”\n\n\n\n  THE MAN IN THE BROWN SUIT\n\n\n\n\n  THE MAN IN THE BROWN SUIT\n\n\n  PROLOGUE\n\n\nNadina, the Russian dancer who had taken Paris by storm, swayed to\nthe sound of the applause, bowed and bowed again. Her narrow black\neyes narrowed themselves still more, the long line of her scarlet\nmouth curved faintly upwards. Enthusiastic Frenchmen continued to\nbeat the ground appreciatively as the curtain fell with a swish,\nhiding the reds and blues and magentas of the bizarre _décors._ In\na swirl of blue and orange draperies the dancer left the stage. A\nbearded gentleman received her enthusiastically in his arms. It\nwas the Manager.\n\n“Magnificent, _petite,_ magnificent,” he cried. “To-night you have\nsurpassed yourself.” He kissed her gallantly on both cheeks in a\nsomewhat matter-of-fact manner.\n\nMadame Nadina accepted the tribute with the ease of long habit and\npassed on to her dressing-room, where bouquets were heaped\ncarelessly everywhere, marvellous garments of futuristic design\nhung on pegs, and the air was hot and sweet with the scent of the\nmassed blossoms and with more sophisticated perfumes and essences.\nJeanne, the dresser, ministered to her mistress, talking incessantly\nand pouring out a stream of fulsome compliment.\n\nA knock at the door interrupted the flow. Jeanne went to answer\nit, and returned with a card in her hand.\n\n“Madame will receive?”\n\n“Let me see.”\n\nThe dancer stretched out a languid hand, but at the sight of the\nname on the card, “Count Sergius Paulovitch,” a sudden flicker of\ninterest came into her eyes.\n\n“I will see him. The maize _peignoir,_ Jeanne, and quickly. And\nwhen the Count comes you may go.”\n\n_“Bien, Madame.”_\n\nJeanne brought the _peignoir,_ an exquisite wisp of corn-coloured\nchiffon and ermine. Nadina slipped into it, and sat smiling to\nherself, whilst one long white hand beat a slow tattoo on the glass\nof the dressing-table.\n\nThe Count was prompt to avail himself of the privilege accorded to\nhim—a man of medium height, very slim, very elegant, very pale,\nextraordinarily weary. In feature, little to take hold of, a man\ndifficult to recognize again if one left his mannerisms out of\naccount. He bowed over the dancer’s hand with exaggerated\ncourtliness.\n\n“Madame, this is a pleasure indeed.”\n\nSo much Jeanne heard before she went out closing the door behind\nher. Alone with her visitor, a subtle change came over Nadina’s\nsmile.\n\n“Compatriots though we are, we will not speak Russian, I think,”\nshe observed.\n\n“Since we neither of us know a word of the language, it might be\nas well,” agreed her guest.\n\nBy common consent, they dropped into English, and nobody, now that\nthe Count’s mannerisms had dropped from him, could doubt that it\nwas his native language. He had, indeed, started life as a\nquick-change music-hall artiste in London.\n\n“You had a great success to-night,” he remarked. “I congratulate\nyou.”\n\n“All the same,” said the woman, “I am disturbed. My position is\nnot what it was. The suspicions aroused during the War have never\ndied down. I am continually watched and spied upon.”\n\n“But no charge of espionage was ever brought against you?”\n\n“Our chief lays his plans too carefully for that.”\n\n“Long life to the ‘Colonel,’” said the Count, smiling. “Amazing\nnews, is it not, that he means to retire? To retire! Just like a\ndoctor, or a butcher, or a plumber——”\n\n“Or any other business man,” finished Nadina. “It should not\nsurprise us. That is what the ‘Colonel’ has always been—an excellent\nman of business. He has organized crime as another man might\norganize a boot factory. Without committing himself, he has planned\nand directed a series of stupendous _coups,_ embracing every branch\nof what we might call his ‘profession.’ Jewel robberies, forgery,\nespionage (the latter very profitable in war-time), sabotage,\ndiscreet assassination, there is hardly anything he has not touched.\nWisest of all, he knows when to stop. The game begins to be\ndangerous?—he retires gracefully—with an enormous fortune!”\n\n“H’m!” said the Count doubtfully. “It is rather—upsetting for all\nof us. We are at a loose end, as it were.”\n\n“But we are being paid off—on a most generous scale!” Something,\nsome undercurrent of mockery in her tone, made the man look at her\nsharply. She was smiling to herself, and the quality of her smile\naroused his curiosity. But he proceeded diplomatically:\n\n“Yes, the ‘Colonel’ has always been a generous paymaster. I\nattribute much of his success to that—and to his invariable plan\nof providing a suitable scapegoat. A great brain, undoubtedly a\ngreat brain! And an apostle of the maxim, ‘If you want a thing done\nsafely, do not do it yourself!’ Here are we, every one of us\nincriminated up to the hilt and absolutely in his power, and not\none of us has anything on him.”\n\nHe paused, almost as though he were expecting her to disagree with\nhim, but she remained silent, smiling to herself as before.\n\n“Not one of us,” he mused. “Still, you know, he is superstitious,\nthe old man. Years ago, I believe, he went to one of these\nfortune-telling people. She prophesied a lifetime of success, but\ndeclared that his downfall would be brought about through a woman.”\n\nHe had interested her now. She looked up eagerly.\n\n“That is strange, very strange! Through a woman, you say?”\n\nHe smiled and shrugged his shoulders.\n\n“Doubtless, now that he has—retired, he will marry. Some young\nsociety beauty, who will disperse his millions faster than he\nacquired them.”\n\nNadina shook her head.\n\n“No, no, that is not the way of it. Listen, my friend, to-morrow\nI go to London.”\n\n“But your contract here?”\n\n“I shall be away only one night. And I go incognito, like Royalty.\nNo one will ever know that I have left France. And why do you think\nthat I go?”\n\n“Hardly for pleasure at this time of year. January, a detestable\nfoggy month! It must be for profit, eh?”\n\n“Exactly.” She rose and stood in front of him, every graceful line\nof her arrogant with pride. “You said just now that none of us had\nanything on the chief. You were wrong. I have. I, a woman, have\nhad the wit and, yes, the courage—for it needs courage—to\ndouble-cross him. You remember the De Beer diamonds?”\n\n“Yes, I remember. At Kimberley, just before the war broke out? I\nhad nothing to do with it, and I never heard the details, the case\nwas hushed up for some reason, was it not? A fine haul too.”\n\n“A hundred thousand pounds worth of stones. Two of us worked\nit—under the ‘Colonel’s’ orders, of course. And it was then that\nI saw my chance. You see, the plan was to substitute some of the\nDe Beer diamonds for some sample diamonds brought from South\nAmerica by two young prospectors who happened to be in Kimberley\nat the time. Suspicion was then bound to fall on them.”\n\n“Very clever,” interpolated the Count approvingly.\n\n“The ‘Colonel’ is always clever. Well, I did my part—but I also\ndid one thing which the ‘Colonel’ had not foreseen. I kept back\nsome of the South American stones—one or two are unique and could\neasily be proved never to have passed through De Beer’s hands. With\nthese diamonds in my possession, I have the whip-hand of my esteemed\nchief. Once the two young men are cleared, his part in the matter\nis bound to be suspected. I have said nothing all these years, I\nhave been content to know that I had this weapon in reserve, but\nnow matters are different. I want my price—and it will be a big,\nI might almost say a staggering price.”\n\n“Extraordinary,” said the Count. “And doubtless you carry these\ndiamonds about with you everywhere?”\n\nHis eyes roamed gently round the disordered room.\n\nNadina laughed softly. “You need suppose nothing of the sort. I am\nnot a fool. The diamonds are in a safe place where no one will\ndream of looking for them.”\n\n“I never thought you a fool, my dear lady, but may I venture to\nsuggest that you are somewhat foolhardy? The ‘Colonel’ is not the\ntype of man to take kindly to being blackmailed, you know.”\n\n“I am not afraid of him,” she laughed. “There is only one man I\nhave ever feared—and he is dead.”\n\nThe man looked at her curiously.\n\n“Let us hope that he will not come to life again, then,” he remarked\nlightly.\n\n“What do you mean?” cried the dancer sharply.\n\nThe Count looked slightly surprised.\n\n“I only meant that a resurrection would be awkward for you,” he\nexplained. “A foolish joke.”\n\nShe gave a sigh of relief.\n\n“Oh, no, he is dead all right. Killed in the war. He was a man who\nonce—loved me.”\n\n“In South Africa?” asked the Count negligently.\n\n“Yes, since you ask it, in South Africa.”\n\n“That is your native country, is it not?”\n\nShe nodded. Her visitor rose and reached for his hat.\n\n“Well,” he remarked, “you know your own business best, but, if I\nwere you, I should fear the ‘Colonel’ far more than any disillusioned\nlover. He is a man whom it is particularly easy to—underestimate.”\n\nShe laughed scornfully.\n\n“As if I did not know him after all these years!”\n\n“I wonder if you do?” he said softly. “I very much wonder if you\ndo.”\n\n“Oh, I am not a fool! And I am not alone in this. The South African\nmail-boat docks at Southampton to-morrow, and on board her is a\nman who has come specially from Africa at my request and who has\ncarried out certain orders of mine. The ‘Colonel’ will have not\none of us to deal with, but two.”\n\n“Is that wise?”\n\n“It is necessary.”\n\n“You are sure of this man?”\n\nA rather peculiar smile played over the dancer’s face.\n\n“I am quite sure of him. He is inefficient, but perfectly\ntrustworthy.” She paused, and then added in an indifferent tone of\nvoice: “As a matter of fact, he happens to be my husband.”\n\n\n\n\n  CHAPTER I\n\n\nEverybody has been at me, right and left, to write this story from\nthe great (represented by Lord Nasby) to the small (represented by\nour late maid of all work, Emily, whom I saw when I was last in\nEngland. “Lor’, miss, what a beyewtiful book you might make out of\nit all—just like the pictures!”).\n\nI’ll admit that I’ve certain qualifications for the task. I was\nmixed up in the affair from the very beginning, I was in the thick\nof it all through, and I was triumphantly “in at the death.” Very\nfortunately, too, the gaps that I cannot supply from my own\nknowledge are amply covered by Sir Eustace Pedler’s diary, of which\nhe has kindly begged me to make use.\n\nSo here goes. Anne Beddingfeld starts to narrate her adventures.\n\nI’d always longed for adventures. You see, my life had such a\ndreadful sameness. My father, Professor Beddingfeld, was one of\nEngland’s greatest living authorities on Primitive Man. He really\nwas a genius—every one admits that. His mind dwelt in Palaeolithic\ntimes, and the inconvenience of life for him was that his body\ninhabited the modern world. Papa did not care for modern man—even\nNeolithic Man he despised as a mere herder of cattle, and he did\nnot rise to enthusiasm until he reached the Mousterian period.\n\nUnfortunately one cannot entirely dispense with modern men. One is\nforced to have some kind of truck with butchers and bakers and\nmilkmen and greengrocers. Therefore, Papa being immersed in the\npast, Mamma having died when I was a baby, it fell to me to\nundertake the practical side of living. Frankly, I hate Palaeolithic\nMan, be he Aurignacian, Mousterian, Chellian, or anything else,\nand though I typed and revised most of Papa’s _Neanderthal Man and\nhis Ancestors,_ Neanderthal men themselves fill me with loathing,\nand I always reflect what a fortunate circumstance it was that they\nbecame extinct in remote ages.\n\nI do not know whether Papa guessed my feelings on the subject,\nprobably not, and in any case he would not have been interested.\nThe opinion of other people never interested him in the slightest\ndegree. I think it was really a sign of his greatness. In the same\nway, he lived quite detached from the necessities of daily life.\nHe ate what was put before him in an exemplary fashion, but seemed\nmildly pained when the question of paying for it arose. We never\nseemed to have any money. His celebrity was not of the kind that\nbrought in a cash return. Although he was a fellow of almost every\nimportant society, and had rows of letters after his name, the\ngeneral public scarcely knew of his existence, and his long learned\nbooks, though adding signally to the sum-total of human knowledge,\nhad no attraction for the masses. Only on one occasion did he leap\ninto the public gaze. He had read a paper before some society on\nthe subject of the young of the chimpanzee. The young of the human\nrace show some anthropoid features, whereas the young of the\nchimpanzee approach more nearly to the human than the adult\nchimpanzee does. That seems to show that whereas our ancestors were\nmore Simian than we are, the chimpanzee’s were of a higher type\nthan the present species—in other words, the chimpanzee is a\ndegenerate. That enterprising newspaper, the _Daily Budget,_ being\nhard up for something spicy, immediately brought itself out with\nlarge headlines. “We are not descended from monkeys, but are\nmonkeys descended from _us?_ Eminent Professor says chimpanzees\nare decadent humans.” Shortly afterwards a reporter called to see\nPapa, and endeavoured to induce him to write a series of popular\narticles on the theory. I have seldom seen Papa so angry. He turned\nthe reporter out of the house with scant ceremony, much to my\nsecret sorrow, as we were particularly short of money at the\nmoment. In fact, for a moment I meditated running after the young\nman and informing him that my father had changed his mind and would\nsend the articles in question. I could easily have written them\nmyself, and the probabilities were that Papa would never have\nlearnt of the transaction, not being a reader of the _Daily Budget._\nHowever, I rejected this course as being too risky, so I merely\nput on my best hat and went sadly down the village to interview\nour justly irate grocer.\n\nThe reporter from the _Daily Budget_ was the only young man who\never came to our house. There were times when I envied Emily, our\nlittle servant, who “walked out” whenever occasion offered with a\nlarge sailor to whom she was affianced. In between times, to “keep\nher hand in” as she expressed it, she walked out with the\ngreengrocer’s young man, and the chemist’s assistant. I reflected\nsadly that I had no one to “keep my hand in” with. All Papa’s\nfriends were aged Professors—usually with long beards. It is true\nthat Professor Peterson once clasped me affectionately and said I\nhad a “neat little waist” and then tried to kiss me. The phrase\nalone dated him hopelessly. No self-respecting female has had a\n“neat little waist” since I was in my cradle.\n\nI yearned for adventure, for love, for romance, and I seemed\ncondemned to an existence of drab utility. The village possessed\na lending library, full of tattered works of fiction, and I enjoyed\nperils and love-making at second hand, and went to sleep dreaming\nof stern, silent Rhodesians, and of strong men who always “felled\ntheir opponent with a single blow.” There was no one in the village\nwho even looked as though he could “fell” an opponent, with a\nsingle blow or with several.\n\nThere was the Kinema too, with a weekly episode of “The Perils of\nPamela.” Pamela was a magnificent young woman. Nothing daunted her.\nShe fell out of aeroplanes, adventured in submarines, climbed\nskyscrapers and crept about in the Underworld without turning a\nhair. She was not really clever, the Master Criminal of the\nUnderworld caught her each time, but as he seemed loath to knock\nher on the head in a simple way, and always doomed her to death in\na sewer-gas chamber or by some new and marvellous means, the hero\nwas always able to rescue her at the beginning of the following\nweek’s episode. I used to come out with my head in a delirious\nwhirl—and then I would get home and find a notice from the Gas\nCompany threatening to cut us off if the outstanding account was\nnot paid!\n\nAnd yet, though I did not suspect it, every moment was bringing\nadventure nearer to me.\n\nIt is possible that there are many people in the world who have\nnever heard of the finding of an antique skull at the Broken Hill\nMine in Northern Rhodesia. I came down one morning to find Papa\nexcited to the point of apoplexy. He poured out the whole story to\nme.\n\n“You understand, Anne? There are undoubtedly certain resemblances\nto the Java skull, but superficial—superficial only. No, here we\nhave what I have always maintained—the ancestral form of the\nNeanderthal race. You grant that the Gibraltar skull is the most\nprimitive of the Neanderthal skulls found? Why? The cradle of the\nrace was in Africa. They passed to Europe——”\n\n“Not marmalade on kippers, papa,” I said hastily, arresting my\nparent’s absent-minded hand. “Yes, you were saying?”\n\n“They passed to Europe on——”\n\nHere he broke down with a bad fit of choking, the result of an\nimmoderate mouthful of kipper-bones.\n\n“But we must start at once,” he declared, as he rose to his feet\nat the conclusion of the meal. “There is no time to be lost. We\nmust be on the spot—there are doubtless incalculable finds to be\nfound in the neighbourhood. I shall be interested to note whether\nthe implements are typical of the Mousterian period—there will be\nthe remains of the primitive ox, I should say, but not those of\nthe woolly rhinoceros. Yes, a little army will be starting soon.\nWe must get ahead of them. You will write to Cook’s to-day, Anne?”\n\n“What about money, papa?” I hinted delicately.\n\nHe turned a reproachful eye upon me.\n\n“Your point of view always depresses me, my child. We must not be\nsordid. No, no, in the cause of science one must not be sordid.”\n\n“I feel Cook’s might be sordid, papa.”\n\nPapa looked pained.\n\n“My dear Anne, you will pay them in ready money.”\n\n“I haven’t got any ready money.”\n\nPapa looked thoroughly exasperated.\n\n“My child, I really cannot be bothered with these vulgar money\ndetails. The bank—I had something from the Manager yesterday,\nsaying I had twenty-seven pounds.”\n\n“That’s your overdraft, I fancy.”\n\n“Ah, I have it! Write to my publishers.”\n\nI acquiesced doubtfully, Papa’s books bringing in more glory than\nmoney. I liked the idea of going to Rhodesia immensely. “Stern\nsilent men,” I murmured to myself in an ecstasy. Then something in\n

In [229]:
book_title = df.iloc[4]["book_title"]
book_title

'The man in the Brown Suit'

In [230]:
 book_id = df.iloc[4]["book_id"]
 book_id

np.int64(4)

In [224]:
book_dfs = []
chapter_regex = re.compile(
    r"^("
    r"PROLOGUE$|"
    r"CHAPTER\s+[IVXLCDM]+\.\s+[^\n]+|"    # CHAPTER I. Title
    r"CHAPTER\s+[IVXLCDM]+$|"              # CHAPTER I
    r"[IVXLCDM]{1,4}\s{1,}[A-Z][^\n]+|"    # I Title
    r"\d+\.\s+[A-Z][^\n]+|"                # 1. Title
    r"\d+\s+[A-Z][^\n]+|"                  # 1 Title
    r"\*+(\s+\*+)+$"                       # * * * * *
    r")$",
    re.MULTILINE
)

for i in range(len(df)):
    try:
        # Get book data from DataFrame row
        book_text = df.iloc[i]["content"]
        book_title = df.iloc[i]["book_title"]
        book_id = df.iloc[i]["book_id"]

        # Step-by-step processing: remove metadata
        book_wo_metadata = delete_metadata(book_text)

        # Generate a unique chapter list for each book using book-specific metadata
        chapter_list = find_chapters(book_wo_metadata, chapter_regex)

        # Debugging: Check the generated chapter list for each book
        print(f"Chapter list for {book_title} (ID {book_id}): {chapter_list}")

        # Find main content for the book (excluding the table of contents)
        book_main_content = find_main_book_content(book_wo_metadata, chapter_list)

        # Splitting into chapters and paragraphs
        paragraph_num = 5
        book_df = extract_chapters_and_paragraphs(book_main_content, chapter_list, book_id, book_title, paragraph_num=paragraph_num)

        # Append the processed DataFrame for the book
        book_dfs.append(book_df)

    except Exception as e:
        print(f"[ERROR] Book ID {df.iloc[i]['book_id']} - {df.iloc[i]['book_title']}: {e}")

# After the loop, combine the processed DataFrames
final_df = pd.concat(book_dfs, ignore_index=True)

Chapter list for The Missing Will (ID 0): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Murder on the Links (ID 1): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Seven Dials Mystery (ID 2): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for Poirot Investigates (ID 3): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The man in the Brown Suit (ID 4): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Mysterious Affair at Styles (ID 5): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Secret Adversary (ID 6): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Big Four (ID 7): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Murder of Roger Ackroyd (ID 8): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Secret of Chimneys (ID 9): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Mystery of the Blue Train (ID 10): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Hunter's Lodge Case (ID 11): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapter list for The Plymouth Express Affair (ID 12): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']

In [225]:
# Create a dictionary to store chapters for each book
book_chapters = {}

for i in range(len(df)):
    try:
        # Get book data from DataFrame row
        book_text = df.iloc[i]["content"]
        book_title = df.iloc[i]["book_title"]
        book_id = df.iloc[i]["book_id"]

        # Step-by-step processing: remove metadata
        book_wo_metadata = delete_metadata(book_text)

        # Use the existing chapter_regex to find the chapters in the book
        chapter_list = find_chapters(book_wo_metadata, chapter_regex)

        # Store the chapter list for the book in the dictionary
        book_chapters[book_title] = chapter_list

        # Debugging: print the chapters found for each book
        print(f"Chapters for {book_title} (ID {book_id}): {chapter_list}")

    except Exception as e:
        print(f"[ERROR] Book ID {df.iloc[i]['book_id']} - {df.iloc[i]['book_title']}: {e}")

Chapters for The Missing Will (ID 0): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Murder on the Links (ID 1): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Seven Dials Mystery (ID 2): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for Poirot Investigates (ID 3): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The man in the Brown Suit (ID 4): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Mysterious Affair at Styles (ID 5): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Secret Adversary (ID 6): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Big Four (ID 7): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Murder of Roger Ackroyd (ID 8): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Secret of Chimneys (ID 9): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Mystery of the Blue Train (ID 10): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Hunter's Lodge Case (ID 11): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
Chapters for The Plymouth Express Affair (ID 12): ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']

In [220]:
final_df

,book_id,book_title,chapter_id,chapter_title,paragraph_id,paragraph_text
0,0,The Missing Will,1,1 A Fellow Traveller,1,I believe that a well-known anecdote exists to...
1,0,The Missing Will,1,1 A Fellow Traveller,2,I’ve lost my only sister?” “Really?” I said po...
2,0,The Missing Will,1,1 A Fellow Traveller,3,mad?” I inquired with a smile. “A regular litt...
3,0,The Missing Will,1,1 A Fellow Traveller,4,"nodded. “You were through it, I suppose?” “Pre..."
4,0,The Missing Will,1,1 A Fellow Traveller,5,"operations, and stared at me with undisguised ..."
...,...,...,...,...,...,...
1750,12,The Plymouth Express Affair,27,28 Journey’s End,1,I have confused memories of the further events...
1751,12,The Plymouth Express Affair,27,28 Journey’s End,2,facts fail to support any theory of her guilt....
1752,12,The Plymouth Express Affair,27,28 Journey’s End,3,be wandering about carrying a souvenir paper-k...
1753,12,The Plymouth Express Affair,27,28 Journey’s End,4,"did I tell you? The shock of joy, it was too m..."
1754,12,The Plymouth Express Affair,27,28 Journey’s End,5,had been in actual fact a fugitive from justic...

In [183]:
# Save to CSV
final_df.to_csv("processed_books.csv", index=False)

# Load it back later
final_df = pd.read_csv("processed_books.csv")

In [184]:
final_df.to_excel("processed_books.xlsx", index=False)
from google.colab import files
files.download("processed_books.xlsx")

### Tokenization and Lemmatisation

In [ ]:
! python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.7.3
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.7.3/en_core_web_trf-3.7.3-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 2.3 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.11/dist-packages (from en-core-web-trf==3.7.3) (3.7.5)
Requirement already satisfied: spacy-curated-transformers<0.3.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from en-core-web-trf==3.7.3) (0.2.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.10.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.26.4)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in /usr/local/lib/python3.11/dist-packages (from spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (2.5.1+cu124)
Requirement already satisfied: regex>=2022 in /usr/local/lib/python3.11/dist-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (2024.11.6)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2025.1.31)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.1.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (3.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (3.4.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.12.0->spacy-curated-transformers<0.3.0,>=0.2.0->en-core-web-trf==3.7.3) (1.3.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-trf==3.7.3) (0.1.2)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import spacy
nlp = spacy.load("en_core_web_trf")

import en_core_web_trf
nlp = en_core_web_trf.load()

doc = nlp("This is a sentence.")
print([(w.text, w.pos_) for w in doc])

/usr/local/lib/python3.11/dist-packages/thinc/shims/pytorch.py:253: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(filelike, map_location=device))
/usr/local/lib/python3.11/dist-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

[('This', 'PRON'), ('is', 'AUX'), ('a', 'DET'), ('sentence', 'NOUN'), ('.', 'PUNCT')]

In [ ]:
import spacy
print(spacy.info())  # Lists installed models

{'spacy_version': '3.7.5', 'location': '/usr/local/lib/python3.11/dist-packages/spacy', 'platform': 'Linux-6.1.85+-x86_64-with-glibc2.35', 'python_version': '3.11.11', 'pipelines': {'en_core_web_lg': '3.7.1', 'en_core_web_trf': '3.7.3', 'en_core_web_sm': '3.7.1'}}

In [ ]:
processed_book_1 = nlp(book_1_main_content)

/usr/local/lib/python3.11/dist-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

In [ ]:
# Tokenization

tokens = []

for token in processed_book_1:
  tokens.append(token.text)

unique_tokens = set(tokens)

print(f'Number of tokens in the preproccessed text: {len(tokens)}')
print(f'Number of unique tokens  in the preproccessed text: {len(unique_tokens)}\n')

print(tokens[:200])

# Lemmatisation

# lemmatised_tokens = []

# for token in processed_book_1:
#   lemmatised_tokens.append(token.lemma_)

# print(lemmatised_tokens[:200])

Number of tokens in the preproccessed text: 87240
Number of unique tokens  in the preproccessed text: 6476

['The', 'Seven', 'Dials', 'Mystery', 'Agatha', 'Christie', 'PRINTING', 'HISTORY', '_', 'Dodd', ',', 'Mead', 'edition', 'published', 'March', '1929', '_', '_', 'Grosset', '&', 'Dunlap', 'edition', 'published', 'February', '1930', '_', '_', 'American', 'Mercury', 'edition', 'published', 'October', '1942', '_', '_', 'Bantam', 'edition', '/', 'January', '1964', '_', '_', 'New', 'Bantam', 'edition', '/', 'March', '1976', '_', '_', 'The', 'Agatha', 'Christie', 'Mystery', 'Collection', '/', 'September', '1986', '_', '_', 'All', 'rights', 'reserved', '.', '_', '_', 'Copyright', '1929', 'by', 'Dodd', ',', 'Mead', '&', 'Company', ',', 'Inc.', '_', '_', 'Copyright', 'renewed', '©', '1957', 'by', 'Agatha', 'Christie', 'Mallowan', '.', '_', 'PRINTED', 'IN', 'THE', 'UNITED', 'STATES', 'OF', 'AMERICA', 'CONTENTS', 'I', 'ON', 'EARLY', 'RISING', 'II', 'CONCERNING', 'ALARUM', 'CLOCKS', 'III', 'THE', 'JOKE', 'THAT', 'FAILED', 'IV', 'A', 'LETTER', 'V', 'THE', 'MAN', 'IN', 'THE', 'ROAD', 'VI', 'SEVEN', 'DIALS', 'AGAIN', 'VII', 'BUNDLE', 'PAYS', 'A', 'CALL', 'VIII', 'VISITORS', 'FOR', 'JIMMY', 'IX', 'PLANS', 'X', 'BUNDLE', 'VISITS', 'SCOTLAND', 'YARD', 'XI', 'DINNER', 'WITH', 'BILL', 'XII', 'INQUIRIES', 'AT', 'CHIMNEYS', 'XIII', 'THE', 'SEVEN', 'DIALS', 'CLUB', 'XIV', 'THE', 'MEETING', 'OF', 'THE', 'SEVEN', 'DIALS', 'XV', 'THE', 'INQUEST', 'XVI', 'THE', 'HOUSE', 'PARTY', 'AT', 'THE', 'ABBEY', 'XVII', 'AFTER', 'DINNER', 'XVIII', 'JIMMY', "'S", 'ADVENTURES', 'XIX', 'BUNDLE', "'S", 'ADVENTURES', 'XX', 'LORAINE', "'S", 'ADVENTURES', 'XXI', 'THE', 'RECOVERY', 'OF', 'THE', 'FORMULA', 'XXII', 'THE', 'COUNTESS', 'RADZKY', "'S", 'STORY', 'XXIII', 'SUPERINTENDENT', 'BATTLE', 'IN', 'CHARGE']

In [ ]:
# true casing

def truecase_text(text):
    doc = nlp(text)
    truecased_tokens = []
    for token in doc:
        if token.ent_type_ in ["PERSON", "GPE", "ORG"]:  # Named Entities should be capitalized
            truecased_tokens.append(token.text.title())
        elif token.is_sent_start:  # Capitalize the first word of each sentence
            truecased_tokens.append(token.text.capitalize())
        else:
            truecased_tokens.append(token.text.lower())

    return " ".join(truecased_tokens)

# Example usage
text = "john and mary went to new york city last summer."
truecased_text = truecase_text(text)
print(truecased_text)

John and Mary went to New York City last summer .

/usr/local/lib/python3.11/dist-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

### Removing stopwords and punctuation

In [ ]:
import nltk
import string
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
print(stop_words)
print(punctuation)

{'or', 'the', 'these', 'ours', "it's", 'for', "mustn't", 've', 'few', 'those', 'they', 'yourselves', 'myself', 're', 'most', "you'll", 'mustn', 'not', 'where', 'no', 'but', 'own', 'up', 'was', "hasn't", 'm', "he'll", 'has', 'mightn', 'off', "that'll", 'both', 'him', 'until', 'in', 'some', 'hers', 'who', 'does', "didn't", 'too', 'our', "weren't", 'once', "she's", 'very', 'only', 'a', "we'll", 'didn', "should've", 'before', 'should', 'why', 'whom', "doesn't", 'yours', 'an', 'been', 'because', 'we', 'below', 'of', 'their', 'against', 'don', 'hasn', 'while', "it'll", 'such', "shouldn't", "don't", 'there', 'being', "i've", "shan't", "he'd", 'needn', 'she', "haven't", 'he', 'himself', 'i', 'y', 'themselves', "you've", 'so', 'then', 'wouldn', 'about', 'ain', 'all', 'wasn', 'won', 'above', "she'll", 'isn', 'theirs', 'through', 'during', 'other', "wouldn't", 'can', 'me', 'this', 'll', 'yourself', 'each', 'its', "we're", 'again', 'you', 'your', 'down', 'had', "couldn't", 'did', 'shan', 'out', "i'll", "he's", 'ma', 'on', "they'll", 'which', "it'd", 'now', 'herself', 'over', 'more', 'her', 'is', "mightn't", 'o', 'it', "they've", "we've", 'be', 'itself', 'if', "they'd", 'my', "you'd", 'd', "needn't", 'after', 'shouldn', 'from', 'how', 'nor', 'at', 'further', 'haven', "isn't", 'than', "aren't", 'that', 'under', 'and', "hadn't", 'his', "wasn't", 'were', "i'd", 'hadn', 'having', 'between', "i'm", 'ourselves', 'doing', 'by', 's', 'any', "she'd", 'couldn', "they're", 'them', 'aren', 'as', 'do', 'same', 'here', 'into', "we'd", 'just', 't', 'weren', "you're", "won't", 'with', 'when', 'are', 'doesn', 'will', 'what', 'have', 'to', 'am'}
{'<', '=', '&', '}', ':', '/', '~', '$', '>', '+', ']', ')', ';', '@', '\\', '|', '(', '.', '%', '!', ',', '*', '-', '`', '_', '#', '^', '{', '[', '?', "'", '"'}

In [ ]:
# Removing punctutation and stopwords

clean_tokens = []
for token in tokens:
  if token in punctuation or token in stop_words:
    continue
  else:
    clean_tokens.append(token)

print(clean_tokens[:100])

# clean_lemmatised_tokens = []
# for token in lemmatised_tokens:
#   if token in punctuation or token in stop_words:
#     continue
#   else:
#     clean_lemmatised_tokens.append(token)

# print(clean_lemmatised_tokens[:100])

print(len(tokens))
print(len(clean_tokens))
# print(len(clean_lemmatised_tokens))

['The', 'Seven', 'Dials', 'Mystery', 'Agatha', 'Christie', 'PRINTING', 'HISTORY', 'Dodd', 'Mead', 'edition', 'published', 'March', '1929', 'Grosset', 'Dunlap', 'edition', 'published', 'February', '1930', 'American', 'Mercury', 'edition', 'published', 'October', '1942', 'Bantam', 'edition', 'January', '1964', 'New', 'Bantam', 'edition', 'March', '1976', 'The', 'Agatha', 'Christie', 'Mystery', 'Collection', 'September', '1986', 'All', 'rights', 'reserved', 'Copyright', '1929', 'Dodd', 'Mead', 'Company', 'Inc.', 'Copyright', 'renewed', '©', '1957', 'Agatha', 'Christie', 'Mallowan', 'PRINTED', 'IN', 'THE', 'UNITED', 'STATES', 'OF', 'AMERICA', 'CONTENTS', 'I', 'ON', 'EARLY', 'RISING', 'II', 'CONCERNING', 'ALARUM', 'CLOCKS', 'III', 'THE', 'JOKE', 'THAT', 'FAILED', 'IV', 'A', 'LETTER', 'V', 'THE', 'MAN', 'IN', 'THE', 'ROAD', 'VI', 'SEVEN', 'DIALS', 'AGAIN', 'VII', 'BUNDLE', 'PAYS', 'A', 'CALL', 'VIII', 'VISITORS', 'FOR']
87240
42098

In [ ]:
#Converting roman numbers into arabic

import roman

print(roman.fromRoman("XIV"))  # Output: 14
print(roman.toRoman(27))  # Output: XXVII

for token in tokens:
  if token in roman:
    token = roman.fromRoman(token)
  continue

print(tokens)

## NER on book content

### NER or raw book main content

In [ ]:
# NER to find all entities

ner_list = []

i = 1
entities_list = []
entities_freq_dict = {}

for ent in processed_book_1.ents:
    print(f'{i}) {ent.text} = {ent.label_}')
    i += 1
    entities_list.append(ent.label_)

for ent_label in entities_list:
  if ent_label not in entities_freq_dict:
    entities_freq_dict[ent_label] = 0
  entities_freq_dict[ent_label] += 1

print(f'The frequencies of unique named entity labels: {entities_freq_dict}')

1) The Seven Dials Mystery = WORK_OF_ART
2) Agatha Christie = PERSON
3) Dodd = PERSON
4) Mead = PERSON
5) March 1929 = DATE
6) Grosset & Dunlap = ORG
7) February 1930 = DATE
8) American Mercury = ORG
9) October 1942 = DATE
10) Bantam = ORG
11) /January 1964 = DATE
12) Bantam = ORG
13) March 1976 = DATE
14) The Agatha Christie Mystery Collection = WORK_OF_ART
15) September 1986 = DATE
16) 1929 = DATE
17) Dodd, Mead & Company, Inc. = ORG
18) 1957 = DATE
19) Agatha Christie Mallowan = PERSON
20) THE UNITED STATES OF AMERICA = GPE
21) II = CARDINAL
22) III = CARDINAL
23) SCOTLAND = GPE
24) XVI = DATE
25) THE ABBEY XVII = EVENT
26) XXIII = DATE
27) GEORGE LOMAX XXX = PERSON
28) CATERHAM = PERSON
29) SEVEN = CARDINAL
30) Jimmy Thesiger = PERSON
31) Chimneys = FAC
32) two = CARDINAL
33) Tredwell = PERSON
34) Tredwell = PERSON
35) Jimmy = PERSON
36) Tredwell = PERSON
37) Wade = PERSON
38) Jimmy = PERSON
39) Jimmy = PERSON
40) a punctual nine-thirty = TIME
41) a quarter past eleven = TIME
42) Coote = PERSON
43) Coote = PERSON
44) the first ten years = DATE
45) Oswald Coote = PERSON
46) morning = TIME
47) eight o'clock = TIME
48) Coote = PERSON
49) Oswald = PERSON
50) Coote = PERSON
51) Rachel = PERSON
52) Coote = PERSON
53) Coote = PERSON
54) Oswald = PERSON
55) Oswald Coote = PERSON
56) first = ORDINAL
57) Works = ORG
58) Oswald = PERSON
59) Works = ORG
60) England = GPE
61) Chimneys = ORG
62) two years = DATE
63) Oswald = PERSON
64) Coote = PERSON
65) three = CARDINAL
66) Coote = PERSON
67) Coote = PERSON
68) Jimmy Thesiger = PERSON
69) Coote = PERSON
70) a few moments = TIME
71) MacDonald = PERSON
72) MacDonald = PERSON
73) Coote = PERSON
74) morning = TIME
75) MacDonald = PERSON
76) night = TIME
77) MacDonald = PERSON
78) Coote = PERSON
79) yesterday = DATE
80) MacDonald = PERSON
81) Caterham = GPE
82) MacDonald = PERSON
83) Coote = PERSON
84) Coote = PERSON
85) MacDonald = PERSON
86) Coote = PERSON
87) Oswald = PERSON
88) Coote = PERSON
89) England = GPE
90) Francis Drake = PERSON
91) Armada = PRODUCT
92) MacDonald = PERSON
93) MacDonald = PERSON
94) Coote = PERSON
95) MacDonald = PERSON
96) William = PERSON
97) Coote = PERSON
98) Scottish = NORP
99) MacDonald = PERSON
100) MacDonald = PERSON
101) Coote = PERSON
102) MacDonald = PERSON
103) Coote = PERSON
104) MacDonald = PERSON
105) William = PERSON
106) Coote = PERSON
107) MacDonald = PERSON
108) Coote = PERSON
109) MacDonald = PERSON
110) Coote = PERSON
111) Jimmy Thesiger = PERSON
112) morning = TIME
113) Coote = PERSON
114) Coote = PERSON
115) Tredwell = PERSON
116) Coote = PERSON
117) Wade = PERSON
118) Wade = PERSON
119) Tredwell = PERSON
120) eleven thirty = TIME
121) yesterday = DATE
122) morning = TIME
123) Wade = PERSON
124) Coote = PERSON
125) twenty minutes to twelve = TIME
126) Tredwell = PERSON
127) one o'clock = TIME
128) Church = ORG
129) Turk = NORP
130) Coote = PERSON
131) second = ORDINAL
132) that morning = TIME
133) Coote = PERSON
134) Oswald = PERSON
135) Bateman = PERSON
136) Coote = PERSON
137) Rupert Bateman = PERSON
138) Oswald = PERSON
139) Jimmy Thesiger = PERSON
140) Morning = TIME
141) Pongo = PERSON
142) Jimmy = PERSON
143) Bateman = PERSON
144) Jimmy = PERSON
145) Bateman = PERSON
146) Bateman = PERSON
147) Pongo = PERSON
148) Pongo = PERSON
149) Jimmy = PERSON
150) Jimmy = PERSON
151) three = CARDINAL
152) two = CARDINAL
153) one = CARDINAL
154) Helen = PERSON
155) Nancy = PERSON
156) third = ORDINAL
157) Socks = PERSON
158) two = CARDINAL
159) Bill Eversleigh = PERSON
160) Ronny Devereux = PERSON
161) Nancy = PERSON
162) Helen = PERSON
163) Jimmy = PERSON
164) Bill Eversleigh = PERSON
165) Gerry Wade = PERSON
166) Ronny Devereux = PERSON
167) Socks = PERSON
168) Coote = PERSON
169) Bill = PERSON
170) Jimmy = PERSON
171) Socks = PERSON
172) Jimmy = PERSON
173) to-morrow morning = TIME
174) Ronny = PERSON
175) seven = TIME
176) Tredwell = PERSON
177) Coote = PERSON
178) Bill = PERSON
179) Bill = PERSON
180) Oswald = PERSON
181) Pongo = PERSON
182) Gerry = PERSON
183) Jimmy = PERSON
184) Socks = PERSON
185) Ronny = PERSON
186) Bill = PERSON
187) Pongo = PERSON
188) Jimmy = PERSON
189) Pongo = PERSON
190) Pongo = PERSON
191) Bateman = PERSON
192) Ronny = PERSON
193) about a dozen = CARDINAL
194) Gerry Wade = PERSON
195) Bill = PERSON
196) Market Basing = FAC
197) Bill = PERSON
198) Ronny = PERSON
199) Jimmy = PERSON
200) Coote = PERSON
201) Jimmy = PERSON
202) Nancy = PERSON
203) Helen = PERSON
204) Coote = PERSON
205) next week = DATE
206) Caterham = PERSON
207) Bill = PERSON
208) Coote = PERSON
209) Bundle Brent = PERSON
210) Caterham = PERSON
211) Socks = PERSON
212) Coote = PERSON
213) Gerald Wade = PERSON
214) Jimmy Thesiger = PERSON
215) Gerald Wade = PERSON
216) Jimmy = PERSON
217) Morning = TIME
218) Coote = PERSON
219) Gerald Wade = PERSON
220) Market Basing = FAC
221) Coote = PERSON
222) Coote = PERSON
223) early in the morning = TIME
224) Wade = PERSON
225) Coote = PERSON
226) Wade = PERSON
227) Coote = PERSON
228) Wade = PERSON
229) Coote = PERSON
230) Wade = PERSON
231) Coote = PERSON
232) Oswald = PERSON
233) Wade = PERSON
234) Foreign Office = ORG
235) eleven o'clock = TIME
236) Coote = PERSON
237) Coote = PERSON
238) Coote = PERSON
239) Market Basing = ORG
240) Bundle = PRODUCT
241) Bill = PERSON
242) Jimmy = PERSON
243) Ronny = PERSON
244) Ronny = PERSON
245) Bundle = PERSON
246) Bill = PERSON
247) Socks = PERSON
248) Murgatroyd = PERSON
249) Murgatroyd's Stores = ORG
250) 10/6 = CARDINAL
251) Murgatroyd = PERSON
252) Nancy = PERSON
253) one day = DATE
254) Helen = PERSON
255) Socks = PERSON
256) Bill = PERSON
257) Jimmy = PERSON
258) the next five minutes = TIME
259) six = CARDINAL
260) Ronny = PERSON
261) Pongo = PERSON
262) Bill = PERSON
263) Coote = PERSON
264) Gerry = PERSON
265) Coote = PERSON
266) MacDonald = PERSON
267) Murgatroyd = PERSON
268) II = CARDINAL
269) Coote = PERSON
270) Oswald = PERSON
271) Oswald = PERSON
272) one = CARDINAL
273) Our Captains of Industry = WORK_OF_ART
274) 7 = CARDINAL
275) Rupert Bateman = PERSON
276) Oswald = PERSON
277) Coote = PERSON
278) Gerald Wade = PERSON
279) Oswald = PERSON
280) Bateman = PERSON
281) Two = CARDINAL
282) Double = ORDINAL
283) Three = CARDINAL
284) Gerald Wade = PERSON
285) Coote = PERSON
286) Gerald Wade's = PERSON
287) Jimmy = PERSON
288) Bill = PERSON
289) one = CARDINAL
290) One = CARDINAL
291) Gerry Wade = PERSON
292) eight = CARDINAL
293) the day = DATE
294) 6:30 A.M. = TIME
295) Bill = PERSON
296) Socks = PERSON
297) Jimmy = PERSON
298) Jimmy = PERSON
299) Pongo = PERSON
300) Bateman = PERSON
301) Jimmy = PERSON
302) Pongo = PERSON
303) Ronny Devereux = PERSON
304) Eight = CARDINAL
305) Gerry = PERSON
306) Jimmy Thesiger = PERSON
307) Ronny = PERSON
308) Gerald = PERSON
309) Jimmy = PERSON
310) Gerry = PERSON
311) Ronny = PERSON
312) Jimmy = PERSON
313) second = ORDINAL
314) Pongo = PRODUCT
315) Bill = PERSON
316) Jimmy = PERSON
317) Socks = PERSON
318) Pongo = PERSON
319) Jimmy = PERSON
320) Pongo = PERSON
321) Pongo = PERSON
322) Jimmy = PERSON
323) one = CARDINAL
324) Bridge = FAC
325) Oswald = PERSON
326) Coote = PERSON
327) Gerald Wade = PERSON
328) Pongo = PERSON
329) Bill Eversleigh = PERSON
330) Ronny Devereux = PERSON
331) about twelve = TIME
332) about an hour = TIME
333) three in the morning = TIME
334) Maria = PERSON
335) Oswald = PERSON
336) Coote = PERSON
337) Oswald = PERSON
338) Gerald Wade's = PERSON
339) Four = CARDINAL
340) four = CARDINAL
341) Gerald Wade = PERSON
342) Coote = PERSON
343) Maria = PERSON
344) Oswald = PERSON
345) Coote = PERSON
346) Gerald Wade = PERSON
347) Oswald = PERSON
348) Coote = PERSON
349) another ten shillings = MONEY
350) Oswald = PERSON
351) Oswald = PERSON
352) Seventeen hundred = MONEY
353) eight pounds = MONEY
354) ten = CARDINAL
355) eight pounds = MONEY
356) Oswald = PERSON
357) Coote = PERSON
358) ten-shilling = MONEY
359) ten shillings = MONEY
360) Oswald = PERSON
361) half-past = TIME
362) Ronny Devereux = PERSON
363) Gerald Wade's = PERSON
364) a quarter to two = TIME
365) about twenty minutes ago = TIME
366) Ronny = PERSON
367) One = CARDINAL
368) three = CARDINAL
369) Bill Eversleigh = PERSON
370) Jimmy Thesiger = PERSON
371) Ronny Devereux = PERSON
372) Rupert Bateman = PERSON
373) Pongo = PERSON
374) Jimmy = PERSON
375) Gerry = PERSON
376) Pongo = PERSON
377) Socks = PERSON
378) Jimmy = PERSON
379) Pongo = PERSON
380) two = CARDINAL
381) minute = TIME
382) two = CARDINAL
383) two = CARDINAL
384) Gerald Wade = PERSON
385) Murgatroyd = PERSON
386) eight = CARDINAL
387) III = CARDINAL
388) Twelve o'clock = TIME
389) Socks = PERSON
390) Ronny Devereux = PERSON
391) Ronny = PERSON
392) Murgatroyd = PERSON
393) Gerald Wade = PERSON
394) Jimmy Thesiger = PERSON
395) Helen = PERSON
396) Nancy = PERSON
397) Rupert Bateman = PERSON
398) Bill = PERSON
399) Socks = PERSON
400) Socks = PERSON
401) Bill = PERSON
402) Socks = PERSON
403) this morning = TIME
404) some minutes past twelve = TIME
405) Socks = PERSON
406) Ronny Devereux = PERSON
407) first = ORDINAL
408) Gerry = PERSON
409) first = ORDINAL
410) Pongo = PERSON
411) Bateman = PERSON
412) Pongo = PERSON
413) Ronny = PERSON
414) Bill = PERSON
415) a few inches = QUANTITY
416) half-past six in the morning = TIME
417) Bill = PERSON
418) Ronny = PERSON
419) Pongo = PERSON
420) Gerry = PERSON
421) twenty past twelve = TIME
422) one = CARDINAL
423) Jimmy = PERSON
424) Cootes = PERSON
425) Bill = PERSON
426) Jimmy = PERSON
427) Gerry = PERSON
428) Ronny = PERSON
429) Ronny = PERSON
430) Tredwell = PERSON
431) Bateman = PERSON
432) this minute = TIME
433) Ronny = PERSON
434) Tredwell = PERSON
435) Jimmy Thesiger = PERSON
436) two = CARDINAL
437) Tredwell = PERSON
438) Ronny = PERSON
439) Wade = PERSON
440) Williams = PERSON
441) Williams = PERSON
442) Tredwell = PERSON
443) Jimmy = PERSON
444) Ronny = PERSON
445) Ronny = PERSON
446) Williams = PERSON
447) Tredwell = PERSON
448) Jimmy = PERSON
449) Williams = PERSON
450) Cartwright = PERSON
451) Oswald = PERSON
452) Bateman = PERSON
453) Tredwell = PERSON
454) Ronny = PERSON
455) Gerry = PERSON
456) Jimmy = PERSON
457) a minute = TIME
458) Ronny = PERSON
459) Gerry Wade's = PERSON
460) Gerry = PERSON
461) Ronny = PERSON
462) Jimmy = PERSON
463) Ronny = PERSON
464) Jimmy = PERSON
465) Ronny = PERSON
466) Ronny = PERSON
467) Jimmy = PERSON
468) Jimmy = PERSON
469) Tredwell = PERSON
470) Jimmy = PERSON
471) Ronny = PERSON
472) Jimmy = PERSON
473) Tredwell = PERSON
474) two = CARDINAL
475) Ronny = PERSON
476) Jimmy = PERSON
477) Cartwright = PERSON
478) Pongo = PERSON
479) Wade = PERSON
480) Ronny = PERSON
481) Ronny = PERSON
482) Jimmy = PERSON
483) Jimmy = PERSON
484) Ronny = PERSON
485) Ronny = PERSON
486) Ronny = PERSON
487) Ronny = PERSON
488) Ronny = PERSON
489) Deane Priory = FAC
490) About twenty miles = QUANTITY
491) Gerry = PERSON
492) Ronny = PERSON
493) Jimmy = PERSON
494) Jimmy = PERSON
495) Ronny = PERSON
496) two = CARDINAL
497) Jimmy = PERSON
498) Jimmy = PERSON
499) Ronny = PERSON
500) Jimmy = PERSON
501) Gerry Wade = PERSON
502) Gerry Wade = PERSON
503) Jimmy = PERSON
504) Ronny = PERSON
505) Jimmy = PERSON
506) Jimmy = PERSON
507) Ronny = PERSON
508) Jimmy = PERSON
509) Ronny = PERSON
510) Gerry = PERSON
511) Jimmy = PERSON
512) Gerry = PERSON
513) Gerry = PERSON
514) Deane Priory = FAC
515) Loraine = PERSON
516) Coker-- = PERSON
517) Jimmy = PERSON
518) Coker = PERSON
519) Coker = PERSON
520) Ronny = PERSON
521) Loraine = PERSON
522) two = CARDINAL
523) Ronny = PERSON
524) Jimmy = PERSON
525) one = CARDINAL
526) Elizabeth = PERSON
527) Jimmy = PERSON
528) Ronny Devereux = PERSON
529) Wade = PERSON
530) Gerry = PERSON
531) Chimneys = FAC
532) Gerry = PERSON
533) Ronny = PERSON
534) Jimmy = PERSON
535) Wade = PERSON
536) Gerry = PERSON
537) Gerry = PERSON
538) Ronny = PERSON
539) Jimmy = PERSON
540) Helen = PERSON
541) Nancy = PERSON
542) Socks = PERSON
543) Ronny = PERSON
544) Wade = PERSON
545) Gerry = PERSON
546) minute = TIME
547) two = CARDINAL
548) Ronny = PERSON
549) Gerry = PERSON
550) Jimmy = PERSON
551) Loraine = PERSON
552) Chimneys = FAC
553) two = CARDINAL
554) first = ORDINAL
555) Ronny = PERSON
556) Jimmy = PERSON
557) Ronny = PERSON
558) Jimmy = PERSON
559) Gerry = PERSON
560) Ronny = PERSON
561) Chimneys = FAC
562) Jimmy = PERSON
563) Coote = PERSON
564) Jimmy = PERSON
565) Coote = PERSON
566) Jimmy = PERSON
567) Ronny = PERSON
568) Gerald Wade's = PERSON
569) Jimmy = PERSON
570) Jimmy = PERSON
571) Jimmy = PERSON
572) Ronny Devereux = PERSON
573) Jimmy = PERSON
574) Jimmy = PERSON
575) one = CARDINAL
576) Gerry Wade = PERSON
577) Ronny = PERSON
578) Jimmy = PERSON
579) Ronny = PERSON
580) Jimmy = PERSON
581) seven = CARDINAL
582) eight = CARDINAL
583) One = CARDINAL
584) Ronny = PERSON
585) Seven = CARDINAL
586) eight = CARDINAL
587) Jimmy = PERSON
588) IV = CARDINAL
589) Caterham = PERSON
590) Eileen Brent = PERSON
591) Bundle = PERSON
592) Coote = PERSON
593) Caterham = PERSON
594) Bundle = PERSON
595) Bundle = PERSON
596) Caterham = PERSON
597) Bundle = PERSON
598) Bundle = PERSON
599) Caterham = PERSON
600) Caterham = PERSON
601) Brents = PERSON
602) second = ORDINAL
603) four years ago = DATE
604) George Lomax = PERSON
605) Coote = PERSON
606) Caterham = PERSON
607) Bundle = PERSON
608) Bundle = PERSON
609) four years ago = DATE
610) Tredwell = ORG
611) Gerry Wade = PERSON
612) Bundle = PERSON
613) Bill = PERSON
614) Caterham = PERSON
615) Bundle = PERSON
616) Caterham = PERSON
617) Raglan = PERSON
618) Bundle = PERSON
619) Caterham = PERSON
620) Wade = PERSON
621) one = CARDINAL
622) Bundle = PERSON
623) Caterham = PERSON
624) Bundle = PERSON
625) MacDonald = PERSON
626) Bundle = PERSON
627) MacDonald = PERSON
628) Bundle = PERSON
629) MacDonald = PERSON
630) MacDonald = PERSON
631) William = PERSON
632) Bundle = PERSON
633) Bundle = PERSON
634) MacDonald = PERSON
635) Caterham = PERSON
636) MacDonald = PERSON
637) Cootes = PERSON
638) MacDonald = PERSON
639) one hoot = QUANTITY
640) two = CARDINAL
641) Coote = PERSON
642) Caterham = PERSON
643) Siddons = PERSON
644) Tredwell = ORG
645) Wade = PERSON
646) Bundle = PERSON
647) Tredwell = PERSON
648) Caterham = PERSON
649) Bundle = PERSON
650) Caterham = PERSON
651) Bundle = PERSON
652) Caterham = PERSON
653) half = CARDINAL
654) Tredwell = PERSON
655) Bundle = PERSON
656) Bundle = PERSON
657) Caterham = PERSON
658) Bundle = PERSON
659) Bundle = PERSON
660) Louisa = PERSON
661) Caterham = PERSON
662) Bundle = PERSON
663) evening = TIME
664) Gerry Wade = PERSON
665) Gerry Wade = PERSON
666) second = ORDINAL
667) Tredwell = PERSON
668) Caterham = PERSON
669) Bundle = PERSON
670) Seven = CARDINAL
671) Bundle = PERSON
672) one = CARDINAL
673) Gerry Wade = PERSON
674) first = ORDINAL
675) Bundle = PERSON
676) the early hours of the morning = TIME
677) Bundle = PERSON
678) Bill Eversleigh = PERSON
679) Bundle = PERSON
680) Bundle = PERSON
681) half = CARDINAL
682) Bundle = PERSON
683) Bundle = PERSON
684) Bundle = PERSON
685) Sept. 21st = DATE
686) September 21st = DATE
687) Bundle = PERSON
688) The 22nd = DATE
689) the day = DATE
690) Gerry Wade = PERSON
691) the very evening = TIME
692) Bundle = PERSON
693) Wednesday = DATE
694) Seven = CARDINAL
695) Lurcher = LOC
696) Bundle = PERSON
697) Seven = CARDINAL
698) London = GPE
699) two = CARDINAL
700) that very night = TIME
701) Gerry Wade = PERSON
702) Bundle = PERSON
703) Gerry Wade = PERSON
704) Bundle = PERSON
705) seven = CARDINAL
706) Bundle = PERSON
707) Caterham = PERSON
708) Hispano = LOC
709) yesterday = DATE
710) Caterham = PERSON
711) a hundred years = DATE
712) Caterham = PERSON
713) Tredwell = ORG
714) only this morning = TIME
715) Bundle = PERSON
716) Tredwell = ORG
717) Bundle = PERSON
718) Caterham = PERSON
719) four years ago = DATE
720) Bundle = PERSON
721) Caterham = PERSON
722) Bundle = PERSON
723) Caterham = PERSON
724) Bundle = PERSON
725) Caterham = PERSON
726) Hispano = PRODUCT
727) Bundle = PERSON
728) Tredwell = PERSON
729) the Boys' Brigade = ORG
730) Caterham = PERSON
731) this morning = TIME
732) Caterham = PERSON
733) Tredwell = PERSON
734) Tredwell = PERSON
735) Bundle = PERSON
736) Klaxon = PRODUCT
737) Katie = PERSON
738) Bundle = PERSON
739) a crisp October day = DATE
740) Bundle = PERSON
741) that morning = TIME
742) Gerald Wade's = PERSON
743) Loraine Wade = PERSON
744) Deane Priory = FAC
745) Bill Eversleigh = PERSON
746) a lovely morning = TIME
747) Hispano = PRODUCT
748) Bundle = PERSON
749) Hispano = PRODUCT
750) Bundle = PERSON
751) Bundle = PERSON
752) Bundle = PERSON
753) Bundle = PERSON
754) the minute = TIME
755) half = CARDINAL
756) Bundle = PERSON
757) Seven = CARDINAL
758) Bundle = PERSON
759) Jimmy Thesiger = PERSON
760) Bundle = PERSON
761) first = ORDINAL
762) Hispano = PRODUCT
763) A couple of miles = QUANTITY
764) Cassell = PERSON
765) Bundle = PERSON
766) Bundle = PERSON
767) Bundle = PERSON
768) Five minutes = TIME
769) ten minutes = TIME
770) a quarter of an hour = TIME
771) twenty minutes = TIME
772) Cassell = PERSON
773) Bundle = PERSON
774) Bundle = PERSON
775) CHAPTER VI SEVEN = EVENT
776) Bundle = PERSON
777) the last three quarters of an hour = TIME
778) quite two minutes = TIME
779) Bundle = PERSON
780) Bundle = PERSON
781) Bundle = PERSON
782) Bundle = PERSON
783) Bundle = PERSON
784) Bundle = PERSON
785) Seven = CARDINAL
786) Cassell = PERSON
787) Bundle = PERSON
788) Bundle = PERSON
789) Albany = FAC
790) Bundle = PERSON
791) Ronald Devereux = PERSON
792) half = CARDINAL
793) Chimneys = LOC
794) Ronny Devereux = PERSON
795) Bill = PERSON
796) the Foreign Office = ORG
797) Bill = PERSON
798) Gerald Wade = PERSON
799) Bundle = PERSON
800) First = ORDINAL
801) Gerald Wade = PERSON
802) Ronny Devereux = PERSON
803) Gerry Wade's = PERSON
804) Ronny Devereux's = PERSON
805) Bundle = PERSON
806) Seven = CARDINAL
807) Gerald Wade = PERSON
808) Seven = CARDINAL
809) the night = TIME
810) Bundle = PERSON
811) Caterham = PERSON
812) Bundle = PERSON
813) London = GPE
814) London = GPE
815) Bundle = PERSON
816) Caterham = PERSON
817) Bundle = PERSON
818) Caterham = PERSON
819) Bundle = PERSON
820) Caterham = PERSON
821) Caterham = PERSON
822) Bundle = PERSON
823) one = CARDINAL
824) Caterham = PERSON
825) Seven = CARDINAL
826) the East End = LOC
827) Seven Sisters = FAC
828) a Jimmy Thesiger = PERSON
829) Caterham = PERSON
830) Seven = CARDINAL
831) Thesiger = PERSON
832) Thesiger = PERSON
833) the Yorkshire Thesigers = NORP
834) Caterham = PERSON
835) Selina = PERSON
836) Thesiger = NORP
837) Bundle = PERSON
838) Caterham = PERSON
839) Bundle = PERSON
840) Bill = PERSON
841) Bundle = PERSON
842) Seven Dials = MONEY
843) Caterham = PERSON
844) Seven Dials = QUANTITY
845) George Lomax = PERSON
846) Tredwell = PERSON
847) Abbey = FAC
848) next week = DATE
849) Seven = CARDINAL
850) Scotland Yard = ORG
851) George = PERSON
852) Bundle = PERSON
853) Cabinet = ORG
854) George Lomax = PERSON
855) State = ORG
856) Foreign Affairs = ORG
857) Bill Eversleigh = PERSON
858) Codders = PERSON
859) Codders = PERSON
860) Gerald Wade's = PERSON
861) Bundle = PERSON
862) some minutes = TIME
863) Loraine Wade = PERSON
864) Gerald Wade = PERSON
865) Wade = PERSON
866) Gerry = PERSON
867) Wade = PERSON
868) Wade = PERSON
869) second = ORDINAL
870) Courts = ORG
871) Wade = PERSON
872) Bundle = PERSON
873) Caterham = PERSON
874) Bundle = PERSON
875) First = ORDINAL
876) this Jimmy Thesiger = PERSON
877) Bill = PERSON
878) Ronny Devereux = PERSON
879) Bill = PERSON
880) Jimmy Thesiger = PERSON
881) Ronny = PERSON
882) Bill = PERSON
883) Loraine Wade = PERSON
884) Seven = CARDINAL
885) Gerry Wade = PERSON
886) BUNDLE = PERSON
887) Bill = PERSON
888) Bundle = PERSON
889) the following morning = TIME
890) Bill = PERSON
891) Bundle = PERSON
892) two = CARDINAL
893) Bill = PERSON
894) Bill = PERSON
895) Bundle = PERSON
896) Bill = PERSON
897) Jimmy Thesiger = PERSON
898) Bundle = PERSON
899) Jimmy = PERSON
900) Bundle = PERSON
901) Jimmy = PERSON

In [ ]:
from spacy import displacy
displacy.render(processed_book_1, style="ent", jupyter=True)

### NER on text out of tokens withouth punctuation and stopwords

In [ ]:
book_1_from_clean_tokens = " ".join(clean_tokens)
print(book_1_from_clean_tokens[:200])

The Seven Dials Mystery Agatha Christie PRINTING HISTORY Dodd Mead edition published March 1929 Grosset Dunlap edition published February 1930 American Mercury edition published October 1942 Bantam ed

In [ ]:
ner_list = []

i = 1
entities_list = []
entities_freq_dict = {}

for ent in nlp(book_1_from_clean_tokens).ents:
    print(f'{i}) {ent.text} = {ent.label_}')
    i += 1
    entities_list.append(ent.label_)

for ent_label in entities_list:
  if ent_label not in entities_freq_dict:
    entities_freq_dict[ent_label] = 0
  entities_freq_dict[ent_label] += 1


print(f'The frequencies of unique named entity labels: {entities_freq_dict}')

/usr/local/lib/python3.11/dist-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

1) Seven = CARDINAL
2) Agatha Christie = PERSON
3) Dodd Mead = ORG
4) March 1929 = DATE
5) Grosset Dunlap = ORG
6) February 1930 = DATE
7) American Mercury = ORG
8) October 1942 = DATE
9) Bantam = ORG
10) January 1964 = DATE
11) New Bantam = ORG
12) March 1976 = DATE
13) The Agatha Christie Mystery Collection = WORK_OF_ART
14) September 1986 = DATE
15) 1929 = DATE
16) Dodd Mead Company Inc. = ORG
17) 1957 = DATE
18) Agatha Christie = PERSON
19) THE UNITED STATES OF AMERICA = GPE
20) II = CARDINAL
21) III = CARDINAL
22) XVI = DATE
23) XXV JIMMY = PERSON
24) GEORGE LOMAX = PERSON
25) CATERHAM = PERSON
26) SEVEN = CARDINAL
27) Jimmy Thesiger = PERSON
28) two = CARDINAL
29) Tredwell = PERSON
30) Tredwell = PERSON
31) Jimmy = PERSON
32) Tredwell = PERSON
33) Wade = PERSON
34) Jimmy = PERSON
35) Jimmy = PERSON
36) nine thirty = TIME
37) quarter past eleven = TIME
38) Coote = PERSON
39) Coote = PERSON
40) first = ORDINAL
41) Oswald Coote = PERSON
42) half minute later = TIME
43) eight o'clock = TIME
44) Lady Coote = PERSON
45) Oswald = PERSON
46) Lady Coote = PERSON
47) Rachel = PERSON
48) Lady Coote = PERSON
49) Lady Coote = PERSON
50) Oswald = PERSON
51) Oswald Coote = PERSON
52) first = ORDINAL
53) Oswald = PERSON
54) England = GPE
55) Marquis Caterham = PERSON
56) two years = DATE
57) Oswald = PERSON
58) Lady Coote = PERSON
59) three = CARDINAL
60) Lady Coote 's = PERSON
61) Coote = PERSON
62) one = CARDINAL
63) Jimmy Thesiger = PERSON
64) Lady Coote = PERSON
65) MacDonald = PERSON
66) MacDonald = PERSON
67) Coote = PERSON
68) MacDonald = PERSON
69) morning = TIME
70) MacDonald = PERSON
71) Coote = PERSON
72) yesterday = DATE
73) one = CARDINAL
74) MacDonald = PERSON
75) Caterham = PERSON
76) one = CARDINAL
77) MacDonald = PERSON
78) Coote = PERSON
79) Coote = PERSON
80) MacDonald = PERSON
81) Coote = PERSON
82) Oswald = PERSON
83) Coote = PERSON
84) England = GPE
85) Francis Drake = PERSON
86) MacDonald = PERSON
87) MacDonald = PERSON
88) Lady Coote = PERSON
89) MacDonald = PERSON
90) William = PERSON
91) Coote = PERSON
92) Scottish = NORP
93) MacDonald = PERSON
94) MacDonald = PERSON
95) Coote = PERSON
96) MacDonald = PERSON
97) Coote = PERSON
98) MacDonald = PERSON
99) William = PERSON
100) Coote = PERSON
101) MacDonald = PERSON
102) Coote = PERSON
103) MacDonald = PERSON
104) Coote = PERSON
105) Jimmy Thesiger = PERSON
106) morning = TIME
107) Coote = PERSON
108) Coote = PERSON
109) Tredwell = GPE
110) Coote = PERSON
111) Wade = PERSON
112) Wade = PERSON
113) Tredwell = GPE
114) eleven thirty = TIME
115) Wade = PERSON
116) Coote = PERSON
117) twenty minutes twelve = TIME
118) Tredwell = PERSON
119) one o'clock = TIME
120) Church = PERSON
121) Coote = PERSON
122) second = ORDINAL
123) Coote = PERSON
124) Oswald = PERSON
125) Bateman = PERSON
126) Coote = PERSON
127) Rupert Bateman = PERSON
128) Oswald = PERSON
129) Jimmy Thesiger = PERSON
130) Morning = DATE
131) Pongo = PERSON
132) Jimmy = PERSON
133) Bateman = PERSON
134) Jimmy = PERSON
135) Bateman = PERSON
136) Bateman = PERSON
137) Pongo = PERSON
138) Pongo = PERSON
139) Jimmy = PERSON
140) Jimmy = PERSON
141) three = CARDINAL
142) two = CARDINAL
143) one = CARDINAL
144) one = CARDINAL
145) Helen = PERSON
146) Nancy = PERSON
147) third = ORDINAL
148) one = CARDINAL
149) Socks = PERSON
150) two = CARDINAL
151) Bill Eversleigh = PERSON
152) Ronny Devereux = PERSON
153) Hallo = PERSON
154) Nancy = PERSON
155) Helen = PERSON
156) Jimmy = PERSON
157) Bill Eversleigh = PERSON
158) Gerry Wade = PERSON
159) Ronny Devereux = PERSON
160) Socks = PERSON
161) Coote = PERSON
162) Bill = PERSON
163) Jimmy = PERSON
164) Socks = PERSON
165) Jimmy = PERSON
166) morrow morning = TIME
167) Ronny = PERSON
168) seven = CARDINAL
169) Stagger = PERSON
170) Tredwell = PERSON
171) Coote = PERSON
172) Bill = PERSON
173) Bill = PERSON
174) Oswald = PERSON
175) Gerry = PERSON
176) Jimmy = PERSON
177) Socks = PERSON
178) Ronny = PERSON
179) Bill = PERSON
180) Pongo = PERSON
181) Jimmy = PERSON
182) Pongo = PERSON
183) one = CARDINAL
184) Pongo = PERSON
185) Bateman = PERSON
186) one = CARDINAL
187) one = CARDINAL
188) one = CARDINAL
189) Ronny = PERSON
190) One = CARDINAL
191) dozen = CARDINAL
192) Gerry Wade = PERSON
193) Bill = PERSON
194) Market Basing = PERSON
195) Bill Ronny = PERSON
196) Jimmy = PERSON
197) Coote = PERSON
198) Jimmy Nancy Helen = PERSON
199) Coote = PERSON
200) next week = DATE
201) Caterham = PERSON
202) Bill = PERSON
203) Coote = PERSON
204) Brent = PERSON
205) Caterham = PERSON
206) Socks = PERSON
207) Lady Coote = PERSON
208) Gerald Wade = PERSON
209) Jimmy Thesiger = PERSON
210) Gerald Wade = PERSON
211) Jimmy = PERSON
212) Morning = TIME
213) Coote = PERSON
214) Gerald Wade = PERSON
215) Market Basing = PERSON
216) Coote = PERSON
217) Lady Coote = PERSON
218) early morning = TIME
219) Wade = PERSON
220) early morning = TIME
221) Coote = PERSON
222) Wade = PERSON
223) Coote = PERSON
224) Wade = PERSON
225) Coote = PERSON
226) Wade = PERSON
227) Coote = PERSON
228) Oswald = PERSON
229) Wade = PERSON
230) Foreign Office = ORG
231) eleven o'clock = TIME
232) Coote = PERSON
233) Lady Coote = PERSON
234) Lady Coote = PERSON
235) Market Basing = ORG
236) Bundle = PERSON
237) Bill = PERSON
238) Jimmy Oh = PERSON
239) mark = PERSON
240) Ronny Ronny = PERSON
241) Bundle = PERSON
242) Bill = PERSON
243) Murgatroyd = PERSON
244) Murgatroyd 's Stores = ORG
245) Murgatroyd = PERSON
246) Nancy = PERSON
247) Helen = PERSON
248) Socks = PERSON
249) one = CARDINAL
250) Bill = PERSON
251) Jimmy = PERSON
252) next five minutes = TIME
253) six = CARDINAL
254) Ronny = PERSON
255) one = CARDINAL
256) Pongo = PERSON
257) Bill = PERSON
258) Coote = PERSON
259) Gerry = PERSON
260) Coote = PERSON
261) MacDonald = PERSON
262) Murgatroyd = PERSON
263) Coote = PERSON
264) Oswald = PERSON
265) Oswald = PERSON
266) Rupert Bateman = PERSON
267) Oswald = PERSON
268) Coote = PERSON
269) Gerald Wade = PERSON
270) Oswald = PERSON
271) Bateman = PERSON
272) Two = CARDINAL
273) Three = CARDINAL
274) Lady Coote = PERSON
275) Gerald Wade = PERSON
276) Coote = PERSON
277) Gerald Wade 's = PERSON
278) Jimmy = PERSON
279) Bill = PERSON
280) one = CARDINAL
281) One = CARDINAL
282) Gerry Wade = PERSON
283) eight = CARDINAL
284) latter day = DATE
285) one = CARDINAL
286) 6:30 A.M. = TIME
287) Bill = PERSON
288) Jimmy = PERSON
289) Jimmy = PERSON
290) Pongo = PERSON
291) Bateman = PERSON
292) Jimmy = PERSON
293) Pongo = PERSON
294) Ronny Devereux = PERSON
295) one = CARDINAL
296) Eight = CARDINAL
297) Gerry ass = PERSON
298) Jimmy Thesiger = PERSON
299) Ronny = PERSON
300) Gerald Do = PERSON
301) Jimmy = PERSON
302) Gerry = PERSON
303) Ronny = PERSON
304) Jimmy = PERSON
305) Pongo = PERSON
306) Bill = PERSON
307) Jimmy = PERSON
308) Pongo = PERSON
309) Jimmy Pongo = PERSON
310) Pongo = PERSON
311) Jimmy = PERSON
312) one = CARDINAL
313) Bridge = PERSON
314) Oswald = PERSON
315) Coote = PERSON
316) Gerald Wade = PERSON
317) Pongo = PERSON
318) Bill Eversleigh = PERSON
319) Ronny Devereux Say = PERSON
320) twelve = CARDINAL
321) three morning = TIME
322) night = TIME
323) Maria = PERSON
324) Oswald = PERSON
325) Coote = PERSON
326) Oswald = PERSON
327) Gerald Wade 's = PERSON
328) Four = CARDINAL
329) rubber = PERSON
330) four = CARDINAL
331) Lucky = PERSON
332) Gerald Wade = PERSON
333) Lucky = PERSON
334) Coote = PERSON
335) Maria = PERSON
336) Oswald = PERSON
337) Coote = PERSON
338) Gerald Wade = PERSON
339) Oswald = PERSON
340) Coote = PERSON
341) another ten shillings = MONEY
342) Oswald = PERSON
343) Oswald = PERSON
344) Seventeen hundred = MONEY
345) eight pounds = MONEY
346) Oswald = PERSON
347) Coote = PERSON
348) extra ten shilling = MONEY
349) ten shillings = MONEY
350) Oswald = PERSON
351) half past = TIME
352) Ronny Devereux = PERSON
353) Gerald Wade = PERSON
354) quarter two = TIME
355) Ronny = PERSON
356) One = CARDINAL
357) three = CARDINAL
358) Bill Eversleigh = PERSON
359) Jimmy Thesiger = PERSON
360) Ronny Devereux = PERSON
361) Rupert Bateman = PERSON
362) Pongo = PERSON
363) Jimmy = PERSON
364) Gerry = PERSON
365) Pongo = PERSON
366) Socks = PERSON
367) Jimmy Pongo = PERSON
368) two = CARDINAL
369) two = CARDINAL
370) two = CARDINAL
371) Gerald Wade = PERSON
372) Murgatroyd = PERSON
373) eight = CARDINAL
374) III = CARDINAL
375) Twelve o'clock = TIME
376) Socks = PERSON
377) Ronny Devereux = PERSON
378) day = DATE
379) Ronny = PERSON
380) Murgatroyd = PERSON
381) Gerald Wade = PERSON
382) Jimmy Thesiger = PERSON
383) Helen = PERSON
384) Nancy = PERSON
385) Rupert Bateman = PERSON
386) Bill = PERSON
387) Socks = PERSON
388) Bill = PERSON
389) morning = TIME
390) Socks = PERSON
391) one = CARDINAL
392) Ronny Devereux = PERSON
393) first = ORDINAL
394) Gerry = PERSON
395) first = ORDINAL
396) Pongo = PERSON
397) Bateman = PERSON
398) Pongo = PERSON
399) Ronny = PERSON
400) Bill = PERSON
401) half past six morning = TIME
402) Bill = PERSON
403) Ronny = PERSON
404) Pongo = PERSON
405) Gerry = PERSON
406) twenty past twelve = TIME
407) one = CARDINAL
408) Jimmy = PERSON
409) Cootes = PERSON
410) Bill = PERSON
411) Jimmy = PERSON
412) Gerry = PERSON
413) Ronny = PERSON
414) Ronny = PERSON
415) Tredwell = PERSON
416) Bateman = PERSON
417) Ronny = PERSON
418) Tredwell = PERSON
419) Jimmy Thesiger = PERSON
420) two = CARDINAL
421) Tredwell = PERSON
422) Ronny = PERSON
423) Wade = PERSON
424) Williams = PERSON
425) Williams = PERSON
426) Tredwell = PERSON
427) Jimmy Ronny = PERSON
428) Ronny = PERSON
429) Williams = PERSON
430) Tredwell = PERSON
431) Jimmy = PERSON
432) butler = PERSON
433) Williams = PERSON
434) Cartwright = PERSON
435) Oswald = PERSON
436) Bateman = PERSON
437) Tredwell = PERSON
438) Ronny = PERSON
439) Gerry = PERSON
440) Jimmy = PERSON
441) Ronny = PERSON
442) Gerry Wade = PERSON
443) Gerry = PERSON
444) Ronny = PERSON
445) Jimmy = PERSON
446) Ronny = PERSON
447) Jimmy = PERSON
448) Ronny = PERSON
449) Ronny = PERSON
450) Jimmy = PERSON
451) Jimmy = PERSON
452) Tredwell = PERSON
453) Jimmy = PERSON
454) Ronny = PERSON
455) Jimmy = PERSON
456) Tredwell = PERSON
457) two = CARDINAL
458) Ronny = PERSON
459) Jimmy = PERSON
460) Cartwright = PERSON
461) Pongo = PERSON
462) Wade = PERSON
463) Ronny = PERSON
464) H'm Well = PERSON
465) Ronny = PERSON
466) Jimmy = PERSON
467) Jimmy = PERSON
468) Ronny = PERSON
469) Ronny = PERSON
470) Ronny = PERSON
471) Ronny = PERSON
472) Ronny = PERSON
473) half = CARDINAL
474) Deane Priory = PERSON
475) About twenty miles = QUANTITY
476) Gerry = PERSON
477) Ronny = PERSON
478) Jimmy = PERSON
479) Jimmy = PERSON
480) Ronny = PERSON
481) two = CARDINAL
482) Jimmy = PERSON
483) Jimmy = PERSON
484) Ronny = PERSON
485) Jimmy = PERSON
486) Gerry Wade = PERSON
487) Gerry Wade = PERSON
488) Jimmy = PERSON
489) Ronny = PERSON
490) Jimmy = PERSON
491) Jimmy = PERSON
492) Ronny = PERSON
493) Jimmy = PERSON
494) Ronny = PERSON
495) Gerry = PERSON
496) Jimmy = PERSON
497) Gerry = PERSON
498) Gerry = PERSON
499) Deane Priory = FAC
500) Loraine = PERSON
501) Coker-- = PERSON
502) Jimmy = PERSON
503) Coker = PERSON
504) Coker = PERSON
505) Ronny = PERSON
506) Loraine = GPE
507) two = CARDINAL
508) Ronny = PERSON
509) Jimmy = PERSON
510) one = CARDINAL
511) Elizabeth = PERSON
512) Jimmy = PERSON
513) This Ronny Devereux = PERSON
514) Wade = PERSON
515) Gerry = PERSON
516) Chimneys = PERSON
517) Gerry = PERSON
518) Ronny = PERSON
519) Jimmy = PERSON
520) Wade = PERSON
521) Gerry = PERSON
522) Gerry = PERSON
523) Ronny = PERSON
524) Jimmy = PERSON
525) Helen Nancy = PERSON
526) Ronny = PERSON
527) Wade = PERSON
528) Gerry = PERSON
529) minute = TIME
530) Ronny = PERSON
531) Gerry = PERSON
532) Jimmy = PERSON
533) Loraine = PERSON
534) Chimneys = PERSON
535) two = CARDINAL
536) first = ORDINAL
537) Ronny = PERSON
538) Jimmy = PERSON
539) Ronny = PERSON
540) Jimmy = PERSON
541) Gerry = PERSON
542) Ronny = PERSON
543) Chimneys = FAC
544) Jimmy = PERSON
545) Coote = PERSON
546) Jimmy = PERSON
547) Coote = PERSON
548) Jimmy = PERSON
549) Ronny = PERSON
550) Gerald Wade 's = PERSON
551) Jimmy = PERSON
552) Jimmy = PERSON
553) Jimmy = PERSON
554) Ronny Devereux = PERSON
555) Jimmy = PERSON
556) Jimmy = PERSON
557) one = CARDINAL
558) Gerry Wade = PERSON
559) Ronny = PERSON
560) Jimmy = PERSON
561) Ronny = PERSON
562) One = CARDINAL
563) Jimmy = PERSON
564) seven eight = CARDINAL
565) Ronny = PERSON
566) Seven = CARDINAL
567) eight = CARDINAL
568) Jimmy = PERSON
569) IV = CARDINAL
570) Caterham = PERSON
571) Eileen Brent = PERSON
572) Bundle = PERSON
573) Coote = PERSON
574) One = CARDINAL
575) Caterham = PERSON
576) Bundle = PERSON
577) Bundle = PERSON
578) Caterham = PERSON
579) Bundle = PERSON
580) Bundle = PERSON
581) Caterham = PERSON
582) Masses = PERSON
583) Caterham = PERSON
584) Brents = PERSON
585) four years ago = DATE
586) George Lomax = PERSON
587) Coote = PERSON
588) Caterham = PERSON
589) Bundle = PERSON
590) Bundle = PERSON
591) four years ago = DATE
592) Tredwell = PERSON
593) Gerry Wade = PERSON
594) Bundle = PERSON
595) Bill = PERSON
596) Caterham = PERSON
597) Bundle = PERSON
598) Caterham = PERSON
599) Raglan = PERSON
600) Bundle = PERSON
601) Caterham = PERSON
602) Half = CARDINAL
603) Wade = PERSON
604) one = CARDINAL
605) Bundle = PERSON
606) Caterham = PERSON
607) Bundle = PERSON
608) MacDonald = PERSON
609) Bundle = PERSON
610) MacDonald = PERSON
611) Bundle = PERSON
612) verra grand = PERSON
613) MacDonald = PERSON
614) MacDonald = PERSON
615) William = PERSON
616) m'lady = PERSON
617) Bundle = PERSON
618) Bundle = PERSON
619) MacDonald = PERSON
620) Caterham = PERSON
621) MacDonald = PERSON
622) Cootes = PERSON
623) MacDonald = PERSON
624) one = CARDINAL
625) two = CARDINAL
626) Coote = PERSON
627) Caterham = PERSON
628) Siddons = PERSON
629) Tredwell = PERSON
630) Wade = PERSON
631) Bundle = PERSON
632) Tredwell = PERSON
633) Caterham = PERSON
634) Bundle = PERSON
635) Caterham = PERSON
636) Bundle = PERSON
637) Caterham = PERSON
638) half = CARDINAL
639) Tredwell = PERSON
640) Bundle = PERSON
641) Bundle = PERSON
642) Caterham = PERSON
643) Bundle = PERSON
644) Bundle = PERSON
645) Louisa = PERSON
646) Caterham = PERSON
647) Bundle = PERSON
648) evening = TIME
649) Gerry Wade = PERSON
650) Gerry Wade = PERSON
651) second = ORDINAL
652) Tredwell = PERSON
653) Caterham = PERSON
654) Bundle = PERSON
655) Seven = CARDINAL
656) Bundle = PERSON
657) one = CARDINAL
658) Gerry Wade = PERSON
659) first = ORDINAL
660) Bundle = PERSON
661) early hours = TIME
662) Bundle = PERSON
663) Bill Eversleigh = PERSON
664) Bundle = PERSON
665) Bundle = PERSON
666) DEAR BILL,-- = PERSON
667) half = CARDINAL
668) Bundle = PERSON
669) Bundle = PERSON
670) first = ORDINAL
671) first = ORDINAL
672) Bundle = PERSON
673) Sept. 21st = DATE
674) September 21st = DATE
675) Bundle = PERSON
676) The 22nd day = DATE
677) Gerry Wade = PERSON
678) evening = TIME
679) Bundle = PERSON
680) Wednesday = DATE
681) Seven Dials = ORG
682) Bundle = PERSON
683) Seven = CARDINAL
684) London = GPE
685) Seven = CARDINAL
686) two = CARDINAL
687) Gerry Wade = PERSON
688) Bundle = PERSON
689) Gerry Wade = PERSON
690) Bundle = PERSON
691) seven = CARDINAL
692) Bundle = PERSON
693) Caterham = PERSON
694) Hispano = GPE
695) yesterday = DATE
696) Caterham = PERSON
697) Caterham = PERSON
698) Tredwell = PERSON
699) morning = TIME
700) Tredwell = PERSON
701) Caterham = PERSON
702) four years ago = DATE
703) Caterham = PERSON
704) Bundle = PERSON
705) Caterham = PERSON
706) Bundle = PERSON
707) Caterham = PERSON
708) Hispano = GPE
709) Bundle = PERSON
710) Tredwell = PERSON
711) Boys Brigade = ORG
712) Caterham = PERSON
713) Caterham = PERSON
714) Tredwell = PERSON
715) Tredwell = PERSON
716) Bundle = PERSON
717) Klaxon = PERSON
718) Katie = PERSON
719) Bundle = PERSON
720) October = DATE
721) Bundle = PERSON
722) Gerald Wade 's = PERSON
723) Loraine Wade = PERSON
724) Deane Priory = PERSON
725) Bill Eversleigh = PERSON
726) morning = TIME
727) Hispano = PERSON
728) Bundle = PERSON
729) Hispano = PRODUCT
730) Mile mile = QUANTITY
731) Bundle = PERSON
732) Bundle = PERSON
733) Bundle = PERSON
734) Bundle = PERSON
735) half = CARDINAL
736) Bundle = PERSON
737) Seven = CARDINAL
738) Bundle = PERSON
739) Jimmy Thesiger = PERSON
740) Bundle = PERSON
741) first = ORDINAL
742) Hispano = PERSON
743) A couple miles = QUANTITY
744) Cassell = PERSON
745) Bundle = PERSON
746) Bundle = PERSON
747) Bundle = PERSON
748) Five minutes = TIME
749) ten minutes = TIME
750) quarter hour = TIME
751) twenty minutes = TIME
752) Cassell = PERSON
753) Bundle = PERSON
754) Bundle = PERSON
755) hedge = PERSON
756) pince nez = PERSON
757) one days = DATE
758) Bundle = PERSON
759) last three quarters hour = DATE
760) quite two minutes = TIME
761) Bundle = PERSON
762) Bundle = PERSON
763) Bundle = PERSON
764) Bundle = PERSON
765) Bundle = PERSON
766) Bundle = PERSON
767) Seven = CARDINAL
768) Cassell = PERSON
769) one = CARDINAL
770) Bundle = PERSON
771) Bundle = PERSON
772) Lads = PERSON
773) Lads = PERSON
774) Ronald Devereux = PERSON
775) Albany Bundle = PERSON
776) Ronald Devereux = PERSON
777) half = CARDINAL
778) Ronny Devereux = PERSON
779) Bill = PERSON
780) Foreign Office = ORG
781) Bill = PERSON
782) Gerald Wade = PERSON
783) Bundle = PERSON
784) First = ORDINAL
785) Gerald Wade = PERSON
786) Ronny Devereux = PERSON
787) Gerry Wade 's = PERSON
788) Ronny Devereux 's = PERSON
789) Bundle = PERSON
790) Seven = CARDINAL
791) Gerald Wade = PERSON
792) Seven = CARDINAL
793) night = TIME
794) Bundle = PERSON
795) Lord Caterham = PERSON
796) Bundle = PERSON
797) London = GPE
798) London = GPE
799) Bundle = PERSON
800) Caterham = PERSON
801) Bundle = PERSON
802) Caterham = PERSON
803) Bundle = PERSON
804) Caterham = PERSON
805) Caterham = PERSON
806) Bundle = PERSON
807) one = CARDINAL
808) Caterham = PERSON
809) East End = LOC
810) Seven = CARDINAL
811) Jimmy Thesiger = PERSON
812) Lord Caterham = PERSON
813) Seven Dials = WORK_OF_ART
814) Thesiger = PERSON
815) Thesiger = PERSON
816) One = CARDINAL
817) Caterham = PERSON
818) Yorkshire Thesigers = NORP
819) Devonshire Thesigers = PERSON
820) Selina = PERSON
821) Thesiger = PERSON
822) Bundle = PERSON
823) Caterham = PERSON
824) Bundle = PERSON
825) Bill Do = PERSON
826) Bundle = PERSON
827) Seven Dials = PERSON
828) Caterham = PERSON
829) Seven Dials = PERSON
830) George Lomax = PERSON
831) Tredwell = PERSON
832) Abbey = PERSON
833) next week = DATE
834) Seven = CARDINAL
835) Scotland Yard = ORG
836) George Bundle = PERSON
837) George Lomax = PERSON
838) State Foreign Affairs = ORG
839) Bill Eversleigh = PERSON
840) Gerald Wade 's = PERSON
841) Bundle = PERSON
842) Loraine Wade = PERSON
843) Gerald Wade = PERSON
844) Wade = PERSON
845) Gerry = PERSON
846) half = CARDINAL
847) Wade = PERSON
848) Wade = PERSON
849) second = ORDINAL
850) Wade = PERSON
851) Bundle = PERSON
852) Caterham = PERSON
853) Bundle = PERSON
854) First = ORDINAL
855) Jimmy Thesiger = PERSON
856) Bill = PERSON
857) Ronny Devereux = PERSON
858) Bill = PERSON
859) Jimmy Thesiger = PERSON
860) Ronny = PERSON
861) Bill = PERSON
862) Loraine Wade = PERSON
863) Seven = CARDINAL
864) Gerry Wade = PERSON
865) CHAPTER VII = EVENT
866) Bill = PERSON
867) morning = TIME
868) Bill = PERSON
869) day two = DATE
870) Bill = PERSON
871) Bill = PERSON
872) Bundle = PERSON
873) Bill = PERSON
874) Jimmy Thesiger = PERSON
875) Bundle = PERSON
876) Jimmy = PERSON
877) Bundle = PERSON
878) Jimmy = PERSON
879) Bundle = PERSON
880) Jimmy Thesiger = PERSON
881) Foreign Office = ORG
882) Bundle = PERSON
883) first = ORDINAL
884) Bill = PERSON
885) Ronny = PERSON
886) Ronny Devereux = PERSON
887) Thesiger = PERSON
888) Ronny-- = PERSON
889) Bundle = PERSON
890) Bill = PERSON
891) Bundle = PERSON
892) first = ORDINAL
893) morning = TIME
894) one = CARDINAL
895) one = CARDINAL
896) Bill = PERSON
897) Ronny = PERSON
898) week end = DATE
899) Gerry Wade = PERSON
900) Bundle = PERSON
901) Bill Ronny 's = PERSON
902) Bill = PERSON

In [ ]:
from spacy import displacy
displacy.render(processed_book_1, style="ent", jupyter=True)

NER on text out of lemmatised tokens withouth punctuation and stopwords

In [ ]:
book_1_from_clean_lemmatised_tokens = " ".join(clean_lemmatised_tokens)
print(book_1_from_clean_lemmatised_tokens[:100])

In [ ]:
ner_list = []

i = 1
entities_list = []
entities_freq_dict = {}

for ent in nlp(book_1_from_clean_tokens).ents:
    print(f'{i}) {ent.text} = {ent.label_}')
    i += 1
    entities_list.append(ent.label_)

for ent_label in entities_list:
  if ent_label not in entities_freq_dict:
    entities_freq_dict[ent_label] = 0
  entities_freq_dict[ent_label] += 1

print(f'The list of unique named entity labels: {entities_list}')
print(f'The frequencies of unique named entity labels: {entities_freq_dict}')

Inside:

## 4. Cleaning and Preprocessing All Books

In [ ]:
# functions for preprocessing
import spacy
nlp = spacy.load("en_core_web_trf")


def truecase_text(text):
    doc = nlp(text)
    truecased_tokens = []
    for token in doc:
        if token.ent_type_ in ["PERSON", "GPE", "ORG"]:  # Named Entities should be capitalized
            truecased_tokens.append(token.text.title())
        elif token.is_sent_start:  # Capitalize the first word of each sentence
            truecased_tokens.append(token.text.capitalize())
        else:
            truecased_tokens.append(token.text.lower())

    return " ".join(truecased_tokens)


def preprocess_book(book, stop_words, punctuation, lemmatisation = False):
  book_tokens = []
  clean_book_tokens = []
  processed_book = nlp(book)
  for token in processed_book:
    if lemmatisation == True:
       book_tokens.append(token.lemma_)
    else:
      book_tokens.append(token.text)
      for token in book_tokens:
      if token in punctuation or token in stop_words:
        continue
      else:
        clean_book_tokens.append(token)
  return clean_book_tokens

In [ ]:
book_1 = final_db[0]

print(book_1)

In [ ]:
book_id_to_extract = 1
book_mask = df['book_id'] == book_id_to_extract
one_book_df = df[book_mask]
print(one_book_df)

In [ ]:
import nltk
import string
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

#preprocessing 1 book
preprocessed_book_1 = preprocess_book(book_1, stop_words, punctuation, lemmatisation = False)
print(preprocessed_book_1[:100])

preprocessed_book_1_lemma = preprocess_book(book, stop_words, punctuation, lemmatisation = True)
print(preprocessed_book_1_lemma[:100]

In [ ]:
#preprocessing each book

##Creating an Inverted Index and Storimg it as a 'pickle' file

Inv Index: https://www.geeksforgeeks.org/inverted-index/

File: https://docs.python.org/3/library/pickle.html#module-pickle

In [ ]:
# Define the documents
document1 = "The quick brown fox jumped over the lazy dog."
document2 = "The lazy dog slept in the sun."

# Step 1: Tokenize the documents
# Convert each document to lowercase and split it into words
tokens1 = document1.lower().split()
tokens2 = document2.lower().split()

# Combine the tokens into a list of unique terms
terms = list(set(tokens1 + tokens2))

# Step 2: Build the inverted index
# Create an empty dictionary to store the inverted index
inverted_index = {}

# For each term, find the documents that contain it
for term in terms:
    documents = []
    if term in tokens1:
        documents.append("Document 1")
    if term in tokens2:
        documents.append("Document 2")
    inverted_index[term] = documents

# Step 3: Print the inverted index
for term, documents in inverted_index.items():
    print(term, "->", ", ".join(documents))

In [ ]:
# Create a list where each element is the 'paragraph_text' from each row
documents = df['paragraph_text'].tolist()

all_tokens = [doc.lower().split() for doc in documents]
all_tokens = [process_book(doc, st) for doc in documents]

terms = set()
for tokens in all_tokens:
    terms.update(tokens)
terms = list(terms)

inverted_index = {}

for term in terms:
    document_ids = []
    for index, tokens in enumerate(all_tokens):
       if term in tokens:
          book_id = final_df.iloc[index]['book_id']
          chapter_id = df.iloc[index]['chapter_id']
          paragraph_id = df.iloc[index]['paragraph_id']
          document_identifier = f"Book {book_id}, Chapter {chapter_id}, Paragraph {paragraph_id}"
          document_ids.append(document_identifier)
       inverted_index[term] = list(set(document_ids)

In [ ]:
i = 10
for term, document_ids in inverted_index.items():
    if i <= 10:
       print(term, "->", ", ".join(document_ids))
    else:
       break

In [ ]:

#storing inverted index in a pickle file

import pickle

# Specify the filename for your pickle file
filename = "inverted_index.pkl"

# Step 1: Open the file in binary write mode ('wb')
with open(filename, 'wb') as f:
    # Step 2: Use pickle.dump() to serialize the inverted index to the file
    pickle.dump(inverted_index, f)

print(f"Inverted index has been successfully saved to '{filename}'")

# To load the inverted index back from the pickle file:

# Step 1: Open the file in binary read mode ('rb')
with open(filename, 'rb') as f:
    # Step 2: Use pickle.load() to deserialize the object from the file
    loaded_inverted_index = pickle.load(f)

print("\nInverted index loaded from the pickle file:")
print(loaded_inverted_index)
print(type(loaded_inverted_index))

##Creating a database in SQLite

https://docs.python.org/3/library/sqlite3.html

In [ ]:
import pandas as pd
import sqlite3

# Sample DataFrame
data = {'col1': [1, 2, 3], 'col2': ['a', 'b', 'c']}
df = pd.DataFrame(data)

# 1. Establish a connection to the SQLite database
#    - If the database file doesn't exist, it will be created.
conn = sqlite3.connect('my_database.db')

# 2. Write the DataFrame to the SQLite table
#    - 'my_table' is the name of the table you want to create in the database.
#    - 'conn' is the database connection object.
#    - 'if_exists' specifies how to handle the table if it already exists:
#      - 'fail': Raise a ValueError.
#      - 'replace': Drop the table before inserting new values.
#      - 'append': Add new values to the existing table.
#    - 'index' determines whether to write the DataFrame index as a column in the table (True/False).
df.to_sql('my_table', conn, if_exists='replace', index=False)

# 3. Close the database connection
conn.close()

print("DataFrame successfully written to my_database.db in the table 'my_table'.")

In [ ]:
import pandas as pd
import sqlite3

# Establish a connection to the SQLite database
conn = sqlite3.connect('my_database.db')

# SQL query to retrieve all data from the 'my_table'
query = "SELECT * FROM my_table"

# Read the data into a pandas DataFrame
df_from_sql = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

print(df_from_sql)

##Creating a Vector Database with SQLite-Vec

In [ ]:
!pip install sqlite_vec

In [ ]:
import sqlite3
import sqlite_vec  # If installed via pip

# Or if you downloaded the library:
# conn.enable_load_extension(True)
# conn.load_extension("./path/to/libsqlitevec.so") # Adjust the path

conn = sqlite3.connect("your_database.db")
conn.enable_load_extension(True)
sqlite_vec.load(conn) # More convenient if installed via pip
cursor = conn.cursor()

In [ ]:
CREATE TABLE IF NOT EXISTS vectors (
    id INTEGER PRIMARY KEY,
    original_id INTEGER, -- Link to your original data
    embedding VECTOR(your_vector_dimension) -- Specify the dimensionality of your vectors
);

In [ ]:
# Assuming you have a list of original IDs and their corresponding embeddings
data_to_insert = [(1, [0.1, 0.2, ..., 0.9]), (2, [0.5, 0.3, ..., 0.1])] # Example

cursor = conn.cursor()
cursor.executemany("INSERT INTO vectors (original_id, embedding) VALUES (?, ?)", data_to_insert)
conn.commit()

In [ ]:
-- Create an HNSW index
CREATE INDEX IF NOT EXISTS vectors_hnsw ON vectors(embedding USING hnsw(32, 2));